"""KATALOG JOBDESK per divisi (Fase 29) — sumber tunggal daftar pekerjaan SIPRO.

Setiap entri = satu jenis pekerjaan nyata yang **bersumber dari fitur yang sudah ada**.
Field penting:
  * `source`      : event (dipicu event sistem) | recurring (jadwal) | manual (ditugaskan)
  * `event`       : tipe event pada Event Bus (untuk source=event)
  * `native`      : True bila task-nya SUDAH dibuat oleh kode modul (jangan dobel-buat)
  * `recurrence`  : daily | weekly | monthly (untuk source=recurring)
  * `assignee`    : record_owner | round_robin | supervisor | all_staff | specific
  * `role_hint`   : peran yang dipakai saat memilih staf (round_robin/all_staff)
  * `verify`      : none | system | supervisor  → JUJUR: apa yang bisa diperiksa mesin,
                    dan apa yang WAJIB dinilai manusia (mis. pendampingan survey/akad)
  * `auto_check`  : kunci pemeriksaan otomatis (lihat workhub.auto_verify)
  * `proof`       : bukti wajib saat menyelesaikan (none/note/photo/document/record/wa_message)
  * `link`        : halaman aplikasi untuk mengerjakan (agar tidak ada CTA mati)
"""

CATALOG = [
    # ==================== SALES & MARKETING ====================
    {"code": "SM-01", "division": "sales_marketing", "title": "Hubungi lead baru (≤5 menit)",
     "source": "event", "event": "lead.created", "native": True, "type": "contact",
     "assignee": "record_owner", "role_hint": "sales", "sla_hours": 0.1, "priority": "urgent",
     "proof": "wa_message", "verify": "system", "auto_check": "lead_contacted", "link": "/leads",
     "desc": "Speed-to-lead: lead wajib dihubungi ≤5 menit sejak masuk (WA/telepon)."},
    {"code": "SM-02", "division": "sales_marketing", "title": "Balas percakapan WA yang belum dijawab",
     "source": "event", "event": "conversation.unanswered", "type": "contact",
     "assignee": "record_owner", "role_hint": "sales", "sla_hours": 2, "priority": "urgent",
     "proof": "wa_message", "verify": "system", "auto_check": "conversation_replied", "link": "/inbox",
     "desc": "Percakapan masuk yang belum dibalas >2 jam otomatis menjadi tugas."},
    {"code": "SM-03", "division": "sales_marketing", "title": "Konfirmasi survey H-1 ke pembeli",
     "source": "event", "event": "appointment.due_soon", "type": "follow_up",
     "assignee": "record_owner", "role_hint": "sales", "sla_hours": 12, "priority": "high",
     "proof": "wa_message", "verify": "system", "auto_check": "conversation_replied",
     "link": "/appointments", "desc": "Kirim pengingat WA H-1 agar survey tidak batal."},
    {"code": "SM-04", "division": "sales_marketing", "title": "Catat hasil survey / kunjungan",
     "source": "event", "event": "appointment.passed", "type": "review",
     "assignee": "record_owner", "role_hint": "sales", "sla_hours": 24, "priority": "high",
     "proof": "note", "verify": "supervisor", "auto_check": None, "link": "/appointments",
     "desc": "Pendampingan & hasil survey adalah penilaian manusia: supervisor memverifikasi."},
    {"code": "SM-05", "division": "sales_marketing", "title": "Susun SPR / booking fee",
     "source": "event", "event": "deal.reserved", "native": True, "type": "todo",
     "assignee": "record_owner", "role_hint": "sales", "sla_hours": 48, "priority": "high",
     "proof": "document", "verify": "system", "auto_check": "document_spr", "link": "/deals",
     "desc": "Terbitkan SPR resmi setelah unit di-hold."},
    {"code": "SM-06", "division": "sales_marketing", "title": "Susun PPJB (maks 30 hari sejak SPR)",
     "source": "event", "event": "deal.booked", "type": "todo",
     "assignee": "record_owner", "role_hint": "sales", "sla_hours": 72, "priority": "urgent",
     "proof": "document", "verify": "system", "auto_check": "document_ppjb", "link": "/documents",
     "desc": "PPJB wajib terbit ≤30 hari; keterlambatan membatalkan booking fee."},
    {"code": "SM-07", "division": "sales_marketing", "title": "Lengkapi KYC pembeli (NIK/NPWP)",
     "source": "event", "event": "customer.created", "type": "todo",
     "assignee": "record_owner", "role_hint": "sales", "sla_hours": 48, "priority": "medium",
     "proof": "record", "verify": "system", "auto_check": "customer_kyc", "link": "/customers",
     "desc": "Data KYC wajib lengkap sebelum PPJB/KPR diajukan."},
    {"code": "SM-08", "division": "sales_marketing", "title": "Dampingi akad / serah terima (BAST)",
     "source": "event", "event": "deal.ppjb", "type": "todo",
     "assignee": "record_owner", "role_hint": "sales", "sla_hours": 168, "priority": "high",
     "proof": "note", "verify": "supervisor", "auto_check": None, "link": "/documents",
     "desc": "Kehadiran & pendampingan fisik — tidak bisa diverifikasi mesin."},
    {"code": "SM-09", "division": "sales_marketing", "title": "Tangani komplain pembeli (SLA)",
     "source": "event", "event": "complaint.created", "native": True, "type": "review",
     "assignee": "round_robin", "role_hint": "sales", "sla_hours": 24, "priority": "high",
     "proof": "note", "verify": "system", "auto_check": "complaint_closed", "link": "/complaints",
     "desc": "Komplain portal pembeli wajib direspons dalam SLA."},
    {"code": "SM-10", "division": "sales_marketing", "title": "Follow-up lead yang masih menimbang",
     "source": "event", "event": "lead.followup_due", "type": "follow_up",
     "assignee": "record_owner", "role_hint": "sales", "sla_hours": 24, "priority": "high",
     "proof": "wa_message", "verify": "system", "auto_check": "lead_activity_recent", "link": "/leads",
     "desc": "Lead nurturing tanpa aktivitas 3 hari otomatis dijadwalkan follow-up WA."},
    {"code": "SM-11", "division": "sales_marketing", "title": "Kirim pengingat pembayaran ke pembeli",
     "source": "event", "event": "collection.reminded", "type": "payment",
     "assignee": "record_owner", "role_hint": "sales", "sla_hours": 24, "priority": "high",
     "proof": "wa_message", "verify": "system", "auto_check": "conversation_replied", "link": "/finance",
     "desc": "Pengingat WA angsuran/DP jatuh tempo (playbook payment_reminder)."},

    {"code": "SM-12", "division": "sales_marketing",
     "title": "Tindak lanjut hasil BI/SLIK ditolak", "source": "event",
     "event": "lead.slik_rejected", "type": "review",
     "assignee": "record_owner", "role_hint": "sales", "sla_hours": 24, "priority": "urgent",
     "proof": "note", "verify": "supervisor", "auto_check": None, "link": "/leads",
     "desc": ("Pra-skrining BI/SLIK ditolak: tawarkan skema tunai/bertahap atau tutup lead "
              "dengan alasan. Keputusannya penilaian manusia \u2192 diverifikasi supervisor.")},

    # ==================== TEKNIS & PROYEK ====================
    {"code": "TK-01", "division": "technical", "title": "Isi buku harian lapangan hari ini",
     "source": "recurring", "recurrence": "daily", "type": "todo",
     "assignee": "all_staff", "role_hint": "site_engineer", "sla_hours": 10, "priority": "high",
     "proof": "record", "verify": "system", "auto_check": "diary_today", "link": "/field",
     "desc": "Catatan harian + foto lapangan wajib diisi setiap hari kerja."},
    {"code": "TK-02", "division": "technical", "title": "Perbarui progres fase konstruksi (mingguan)",
     "source": "recurring", "recurrence": "weekly", "type": "review",
     "assignee": "supervisor", "role_hint": "project_manager", "sla_hours": 48, "priority": "medium",
     "proof": "record", "verify": "system", "auto_check": "progress_updated", "link": "/construction",
     "desc": "Bobot fase & progres unit diperbarui agar kurva S dan portal pembeli akurat."},
    {"code": "TK-03", "division": "technical", "title": "Tutup temuan punch list (foto bukti perbaikan)",
     "source": "event", "event": "punch.created", "native": True, "type": "todo",
     "assignee": "record_owner", "role_hint": "site_engineer", "sla_hours": 72, "priority": "high",
     "proof": "photo", "verify": "system", "auto_check": "punch_fixed", "link": "/field",
     "desc": "Temuan wajib ditutup dengan foto SESUDAH (bukti kerja berpasangan)."},
    {"code": "TK-04", "division": "technical", "title": "Jalankan inspeksi QC per fase",
     "source": "recurring", "recurrence": "weekly", "type": "inspection",
     "assignee": "round_robin", "role_hint": "site_engineer", "sla_hours": 72, "priority": "medium",
     "proof": "record", "verify": "system", "auto_check": "inspection_finalized", "link": "/construction",
     "desc": "Checklist QC per fase (struktur/MEP/handover) dijalankan berkala."},
    {"code": "TK-05", "division": "technical", "title": "Perbaiki temuan QC yang GAGAL",
     "source": "event", "event": "qc.failed", "native": True, "type": "todo",
     "assignee": "record_owner", "role_hint": "site_engineer", "sla_hours": 48, "priority": "urgent",
     "proof": "photo", "verify": "supervisor", "auto_check": None, "link": "/construction",
     "desc": "QC gagal menahan fase (qc_hold); perbaikan dinilai ulang oleh supervisor."},
    {"code": "TK-06", "division": "technical", "title": "Ajukan requisition & opname material",
     "source": "event", "event": "material.overbudget", "native": True, "type": "review",
     "assignee": "supervisor", "role_hint": "project_manager", "sla_hours": 48, "priority": "high",
     "proof": "note", "verify": "supervisor", "auto_check": None, "link": "/materials",
     "desc": "Pemakaian melewati RAB wajib ditinjau sebelum pembelian berikutnya."},
    {"code": "TK-07", "division": "technical", "title": "Verifikasi GRN / 3-way match tagihan",
     "source": "event", "event": "grn.flagged", "native": True, "type": "approval",
     "assignee": "supervisor", "role_hint": "project_manager", "sla_hours": 48, "priority": "urgent",
     "proof": "note", "verify": "supervisor", "auto_check": None, "link": "/procurement",
     "desc": "Tagihan > nilai barang diterima/PO ditandai; wajib diperiksa manusia (anti-fraud)."},
    {"code": "TK-08", "division": "technical", "title": "Urus izin yang mendekati jatuh tempo",
     "source": "event", "event": "permit.due_soon", "native": True, "type": "review",
     "assignee": "supervisor", "role_hint": "project_manager", "sla_hours": 168, "priority": "high",
     "proof": "document", "verify": "supervisor", "auto_check": None, "link": "/permits",
     "desc": "Izin kedaluwarsa menghentikan pembangunan — diproses sebelum tenggat."},
    {"code": "TK-09", "division": "technical", "title": "Verifikasi termin/opname subkontraktor",
     "source": "event", "event": "progress_claim.submitted", "type": "approval",
     "assignee": "supervisor", "role_hint": "project_manager", "sla_hours": 72, "priority": "high",
     "proof": "note", "verify": "supervisor", "auto_check": None, "link": "/subcon",
     "desc": "Opname fisik dicek sebelum tagihan AP terbit (segregasi tugas)."},
    # -------- Fase 31: jadwal pembangunan per unit (task dibuat oleh build_engine) --------
    {"code": "TK-10", "division": "technical",
     "title": "Kerjakan item jadwal unit (bukti foto + checklist mutu)",
     "source": "event", "event": "build.item_ready", "native": True, "type": "todo",
     "assignee": "record_owner", "role_hint": "site_engineer", "sla_hours": 48,
     "priority": "high", "proof": "photo", "verify": "supervisor", "auto_check": None,
     "link": "/construction",
     "desc": ("Item pekerjaan yang gerbangnya sudah terbuka (pendahulu terverifikasi & "
              "waktu tunggu terlewati) wajib dikerjakan lalu diajukan dengan bukti.")},
    {"code": "TK-11", "division": "technical", "title": "Verifikasi hasil pekerjaan unit",
     "source": "event", "event": "build.item_submitted", "native": True, "type": "approval",
     "assignee": "supervisor", "role_hint": "project_manager", "sla_hours": 24,
     "priority": "high", "proof": "note", "verify": "none", "auto_check": None,
     "link": "/construction",
     "desc": ("Foto bukti + checklist mutu diperiksa supervisor. Pengaju TIDAK boleh "
              "memverifikasi pekerjaannya sendiri (pemisahan tugas).")},
    {"code": "TK-12", "division": "technical",
     "title": "Perbaiki pekerjaan unit yang dikembalikan",
     "source": "event", "event": "build.item_rework", "native": True, "type": "todo",
     "assignee": "record_owner", "role_hint": "site_engineer", "sla_hours": 48,
     "priority": "urgent", "proof": "photo", "verify": "supervisor", "auto_check": None,
     "link": "/construction",
     "desc": "Hasil yang ditolak supervisor wajib diperbaiki dan diajukan ulang."},
    {"code": "TK-13", "division": "technical",
     "title": "Kejar item pekerjaan unit yang TELAT (isi penyebab + rencana pemulihan)",
     "source": "event", "event": "build.item_late", "native": True, "type": "review",
     "assignee": "record_owner", "role_hint": "site_engineer", "sla_hours": 24,
     "priority": "urgent", "proof": "note", "verify": "supervisor", "auto_check": None,
     "link": "/construction",
     "desc": ("Eskalasi berjenjang: telat ≥1 hari ke staf+supervisor, ≥3 hari ke direksi, "
              "≥7 hari peringatan kritis.")},
    # -------- Fase 32: laporan mingguan pembangunan untuk direksi & manajer proyek --------
    {"code": "TK-14", "division": "technical",
     "title": "Baca laporan mingguan pembangunan",
     "source": "event", "event": "build.weekly_report", "native": True, "type": "review",
     "assignee": "supervisor", "role_hint": "project_manager", "sla_hours": 48,
     "priority": "medium", "proof": "note", "verify": "none", "auto_check": None,
     "link": "/construction",
     "desc": ("Ringkasan progres tiap rumah per pekan (rencana vs realisasi, pekerjaan "
              "telat, penyebab dominan) — dikirim otomatis setiap Senin, bisa diunduh PDF.")},

    # ==================== DIGITAL MARKETING ====================
    {"code": "DM-01", "division": "digital_marketing", "title": "Pantau lead iklan & CPL hari ini",
     "source": "recurring", "recurrence": "daily", "type": "review",
     "assignee": "all_staff", "role_hint": "dm_staff", "sla_hours": 8, "priority": "medium",
     "proof": "note", "verify": "none", "auto_check": None, "link": "/automation",
     "desc": "Periksa jumlah lead per campaign & biaya per lead; catat temuan."},
    {"code": "DM-02", "division": "digital_marketing", "title": "Tangani lead capture gagal / ganda",
     "source": "event", "event": "capture.failed", "type": "todo",
     "assignee": "round_robin", "role_hint": "dm_staff", "sla_hours": 12, "priority": "high",
     "proof": "note", "verify": "none", "auto_check": None, "link": "/automation",
     "desc": "Payload webhook gagal/duplikat harus ditindak agar lead iklan tidak bocor."},
    {"code": "DM-03", "division": "digital_marketing", "title": "Kelola & ajukan template WhatsApp",
     "source": "manual", "type": "todo",
     "assignee": "round_robin", "role_hint": "dm_staff", "sla_hours": 72, "priority": "medium",
     "proof": "record", "verify": "system", "auto_check": "wa_template_exists", "link": "/automation",
     "desc": "Template pra-approved wajib tersedia agar sesi 24 jam bisa dibuka ulang."},
    {"code": "DM-04", "division": "digital_marketing", "title": "Jalankan blasting promo tersegmentasi",
     "source": "recurring", "recurrence": "weekly", "type": "todo",
     "assignee": "round_robin", "role_hint": "dm_staff", "sla_hours": 48, "priority": "medium",
     "proof": "record", "verify": "system", "auto_check": "broadcast_recent", "link": "/automation",
     "desc": "Kirim promo ke segmen (stage/skor/sumber) memakai template — hindari spam."},
    {"code": "DM-05", "division": "digital_marketing", "title": "Kelola tautan showroom publik",
     "source": "manual", "type": "todo",
     "assignee": "supervisor", "role_hint": "dm_supervisor", "sla_hours": 72, "priority": "low",
     "proof": "note", "verify": "none", "auto_check": None, "link": "/site-plan",
     "desc": "Aktifkan/putar ulang tautan showroom & pastikan harga sesuai kebijakan."},
    {"code": "DM-06", "division": "digital_marketing", "title": "Audit atribusi & umpan balik CAPI",
     "source": "recurring", "recurrence": "weekly", "type": "review",
     "assignee": "round_robin", "role_hint": "dm_staff", "sla_hours": 48, "priority": "medium",
     "proof": "note", "verify": "none", "auto_check": None, "link": "/automation",
     "desc": "Pastikan event Lead/Booking/Purchase terkirim ke platform iklan."},
    {"code": "DM-07", "division": "digital_marketing", "title": "Laporan performa iklan mingguan",
     "source": "recurring", "recurrence": "weekly", "type": "review",
     "assignee": "supervisor", "role_hint": "dm_supervisor", "sla_hours": 72, "priority": "medium",
     "proof": "note", "verify": "supervisor", "auto_check": None, "link": "/automation",
     "desc": "Ringkas CPL/CPQL & konversi per campaign untuk rapat mingguan."},
    {"code": "DM-08", "division": "digital_marketing", "title": "Kirim pengingat WA sesuai stage lead",
     "source": "recurring", "recurrence": "daily", "type": "follow_up",
     "assignee": "round_robin", "role_hint": "dm_staff", "sla_hours": 12, "priority": "medium",
     "proof": "record", "verify": "system", "auto_check": "broadcast_recent", "link": "/automation",
     "desc": "Playbook per stage: sapaan, follow-up, pengingat survey, pengingat bayar."},

    # ==================== KEUANGAN ====================
    {"code": "FN-01", "division": "finance", "title": "Tagih AR yang jatuh tempo",
     "source": "event", "event": "ar.overdue", "type": "payment",
     "assignee": "round_robin", "role_hint": "finance", "sla_hours": 24, "priority": "urgent",
     "proof": "note", "verify": "system", "auto_check": "ar_followed_up", "link": "/finance",
     "desc": "Tagihan pembeli lewat jatuh tempo wajib ditindak (kirim pengingat/telepon)."},
    {"code": "FN-02", "division": "finance", "title": "Verifikasi & posting penerimaan kas",
     "source": "event", "event": "payment.received", "type": "approval",
     "assignee": "round_robin", "role_hint": "finance", "sla_hours": 24, "priority": "high",
     "proof": "document", "verify": "supervisor", "auto_check": None, "link": "/finance",
     "desc": "Bukti transfer dicocokkan dengan jadwal AR sebelum diakui."},
    {"code": "FN-03", "division": "finance", "title": "Bayar termin subkon setelah QC lolos",
     "source": "event", "event": "ap.approved", "type": "payment",
     "assignee": "round_robin", "role_hint": "finance", "sla_hours": 72, "priority": "high",
     "proof": "document", "verify": "supervisor", "auto_check": None, "link": "/finance",
     "desc": "Pembayaran hanya setelah gerbang QC lolos (aturan invarian)."},
    {"code": "FN-04", "division": "finance", "title": "Rilis retensi yang jatuh tempo",
     "source": "recurring", "recurrence": "monthly", "type": "payment",
     "assignee": "round_robin", "role_hint": "finance", "sla_hours": 120, "priority": "medium",
     "proof": "note", "verify": "supervisor", "auto_check": None, "link": "/finance",
     "desc": "Retensi ditahan dilepas sesuai jadwal setelah masa pemeliharaan."},
    {"code": "FN-05", "division": "finance", "title": "Setujui kas bon & tagih pertanggungjawaban",
     "source": "event", "event": "cashbon.submitted", "type": "approval",
     "assignee": "supervisor", "role_hint": "finance_manager", "sla_hours": 24, "priority": "high",
     "proof": "note", "verify": "supervisor", "auto_check": None, "link": "/petty-cash",
     "desc": "Kas bon disetujui, lalu bukti pengeluaran ditagih sampai lunas."},
    {"code": "FN-06", "division": "finance", "title": "Posting jurnal penyusutan bulanan",
     "source": "recurring", "recurrence": "monthly", "type": "todo",
     "assignee": "round_robin", "role_hint": "finance", "sla_hours": 120, "priority": "medium",
     "proof": "record", "verify": "system", "auto_check": "depreciation_posted", "link": "/fixed-assets",
     "desc": "Penyusutan aset tetap diposting sekali per periode (idempoten)."},
    {"code": "FN-07", "division": "finance", "title": "Tutup buku periode bulanan",
     "source": "recurring", "recurrence": "monthly", "type": "approval",
     "assignee": "supervisor", "role_hint": "finance_manager", "sla_hours": 168, "priority": "high",
     "proof": "note", "verify": "supervisor", "auto_check": None, "link": "/accounting",
     "desc": "Periode dikunci setelah rekonsiliasi agar laporan tidak berubah."},
    {"code": "FN-08", "division": "finance", "title": "Siapkan & lapor pajak bulanan",
     "source": "recurring", "recurrence": "monthly", "type": "todo",
     "assignee": "round_robin", "role_hint": "finance", "sla_hours": 168, "priority": "high",
     "proof": "document", "verify": "supervisor", "auto_check": None, "link": "/tax",
     "desc": "PPN/PPh/BPHTB disiapkan dari worksheet lalu disetorkan."},
    {"code": "FN-09", "division": "finance", "title": "Bayar angsuran pinjaman korporat",
     "source": "recurring", "recurrence": "monthly", "type": "payment",
     "assignee": "round_robin", "role_hint": "finance", "sla_hours": 120, "priority": "high",
     "proof": "document", "verify": "supervisor", "auto_check": None, "link": "/corporate-financing",
     "desc": "Angsuran pokok+bunga dibayar tepat waktu (hindari denda)."},
    {"code": "FN-10", "division": "finance", "title": "Bayar marketing fee agen terverifikasi",
     "source": "event", "event": "commission.approved", "type": "payment",
     "assignee": "round_robin", "role_hint": "finance", "sla_hours": 72, "priority": "medium",
     "proof": "document", "verify": "supervisor", "auto_check": None, "link": "/marketing-fee",
     "desc": "Fee agen dibayar setelah verifikasi dokumen & pelunasan pembeli."},
    # Fase 45 — anggaran mendekati/melewati batas. Tugas ini SENGAJA ada: peringatan yang
    # hanya berupa notifikasi mudah dilewatkan, sedangkan overbudget menuntut keputusan
    # (revisi anggaran beralasan atau change order). Penerimanya adalah `owner_role` item
    # anggaran tersebut (dikirim lewat `assignee_override`), jadi yang ditagih adalah orang
    # yang memang memegang pos biaya itu.
    {"code": "FN-11", "division": "finance",
     "title": "Tindaklanjuti anggaran yang mendekati/melewati batas",
     "source": "event", "event": "budget.alert", "type": "approval",
     "assignee": "supervisor", "role_hint": "finance_manager", "sla_hours": 48,
     "priority": "high", "proof": "note", "verify": "supervisor", "auto_check": None,
     "link": "/boq?hub=realisasi",
     "desc": "Exposure (realisasi + komitmen) sudah melewati ambang peringatan. Putuskan: "
             "revisi anggaran beralasan, change order, atau tahan komitmen berikutnya."},
]

BY_CODE = {j["code"]: j for j in CATALOG}

# Event yang memicu pembuatan task jobdesk (dipakai untuk registrasi handler Event Bus).
EVENT_CODES: dict = {}
for _j in CATALOG:
    if _j.get("source") == "event" and _j.get("event"):
        EVENT_CODES.setdefault(_j["event"], []).append(_j["code"])

RECURRING = [j["code"] for j in CATALOG if j.get("source") == "recurring"]


def defaults(code: str) -> dict:
    """Konfigurasi bawaan sebuah jobdesk (sebelum di-override supervisor)."""
    j = BY_CODE.get(code) or {}
    return {
        "code": code, "division": j.get("division"), "title": j.get("title"),
        "description": j.get("desc"), "source": j.get("source"), "event": j.get("event"),
        "recurrence": j.get("recurrence"), "type": j.get("type", "todo"),
        "assignee_rule": j.get("assignee", "round_robin"), "assignee_email": None,
        "role_hint": j.get("role_hint"), "sla_hours": j.get("sla_hours", 24),
        "priority": j.get("priority", "medium"), "proof_kind": j.get("proof", "note"),
        "verify_mode": j.get("verify", "none"), "auto_check": j.get("auto_check"),
        "link": j.get("link"), "native": bool(j.get("native")), "is_active": True,
    }
