// Fase 43 — Kampanye & Biaya Iklan + Atribusi/CAPI + Status Integrasi.
export const ADS = {
  // hub kampanye
  page: "ads-page",
  hubTab: "ads-hub-tab",
  // master kampanye
  campaignsTable: "ads-campaigns-table",
  campaignRow: "ads-campaign-row",
  campaignAdd: "ads-campaign-add",
  campaignForm: "ads-campaign-form",
  formName: "ads-campaign-name",
  formPlatform: "ads-campaign-platform",
  formObjective: "ads-campaign-objective",
  formStatus: "ads-campaign-status",
  formExternalId: "ads-campaign-external-id",
  formProject: "ads-campaign-project",
  formBudgetDaily: "ads-campaign-budget-daily",
  formBudgetTotal: "ads-campaign-budget-total",
  formStart: "ads-campaign-start",
  formEnd: "ads-campaign-end",
  formAudience: "ads-campaign-audience",
  formSubmit: "ads-campaign-submit",
  // biaya iklan
  spendTable: "ads-spend-table",
  spendRow: "ads-spend-row",
  spendAdd: "ads-spend-add",
  spendForm: "ads-spend-form",
  spendCampaign: "ads-spend-campaign",
  spendDate: "ads-spend-date",
  spendAmount: "ads-spend-amount",
  spendAmountPreview: "ads-spend-amount-preview",
  spendAdset: "ads-spend-adset",
  spendImpressions: "ads-spend-impressions",
  spendClicks: "ads-spend-clicks",
  spendLeads: "ads-spend-leads",
  spendSubmit: "ads-spend-submit",
  spendChart: "ads-spend-chart",
  spendPeriod: "ads-spend-period",
  syncBtn: "ads-sync-button",
  // impor CSV
  importBtn: "ads-import-button",
  importDialog: "ads-import-dialog",
  importFile: "ads-import-file",
  importText: "ads-import-text",
  importMappingToggle: "ads-import-mapping-toggle",
  importMappingField: "ads-import-mapping-field",
  importPreview: "ads-import-preview",
  importCommit: "ads-import-commit",
  importTemplate: "ads-import-template",
  importSummary: "ads-import-summary",
  importRowsTable: "ads-import-rows",
  importRow: "ads-import-row",
  importsTable: "ads-imports-table",
  importsRow: "ads-imports-row",
  importDetail: "ads-import-detail",
  // kinerja
  perfTable: "ads-performance-table",
  perfRow: "ads-performance-row",
  perfKpi: "ads-performance-kpi",
  costWarning: "ads-cost-warning",
  costBadge: "ads-cost-badge",
  sourceLabel: "ads-source-label",
  rangeFrom: "ads-range-from",
  rangeTo: "ads-range-to",
  rangeApply: "ads-range-apply",
  // atribusi & CAPI
  attrPage: "attribution-page",
  attrTable: "attribution-table",
  attrRow: "attribution-row",
  attrLevel: "attribution-level",
  channelMix: "attribution-channel-mix",
  capiTable: "capi-events-table",
  capiRow: "capi-event-row",
  capiResend: "capi-event-resend",
  capiSummary: "capi-summary",
  // status integrasi
  healthTable: "integration-health-table",
  healthRow: "integration-health-row",
  healthProbe: "integration-health-probe",
};

// Webhook lead mitra (Fase 43, dipakai di profil mitra).
export const PARTNER_HOOK = {
  card: "partner-webhook-card",
  rotate: "partner-webhook-rotate",
  dialog: "partner-webhook-dialog",
  token: "partner-webhook-token",
  url: "partner-webhook-url",
};
