// Phase 14 — Appointment & Survey (EPIC 1.2) + Commission Breakdown (EPIC 1.6)
export const APPTS = {
  page: "appointments-page",
  calendar: "appointments-calendar",
  agenda: "appointments-agenda",
  agendaItem: "appointment-agenda-item",
  statusFilter: "appointments-status-filter",
  detail: "appointment-detail",
  statusSelect: "appointment-status-select",
  statusApplyBtn: "appointment-status-apply",
  // Fase 63 — agenda kerja lengkap: tabel (cari/filter/urut) + buat & ubah agenda
  createBtn: "agenda-create-button",
  form: "agenda-form",
  formKind: "agenda-form-kind",
  formTitle: "agenda-form-title",
  formType: "agenda-form-type",
  formDate: "agenda-form-date",
  formTime: "agenda-form-time",
  formLead: "agenda-form-lead",
  formLeadSearch: "agenda-form-lead-search",
  formLocation: "agenda-form-location",
  formNotes: "agenda-form-notes",
  formParticipants: "agenda-form-participants",
  formParticipant: "agenda-form-participant",
  formSubmit: "agenda-form-submit",
  table: "agenda-table",
  tableRow: "agenda-table-row",
  tableSearch: "agenda-table-search",
  rangeFilter: "agenda-range-filter",
  editBtn: "agenda-edit-button",
  dayCreateBtn: "agenda-day-create-button",
};

export const SURVEY = {
  section: "survey-section",
  startBtn: "survey-start-button",
  checklistItem: "survey-checklist-item",
  checklistSelect: "survey-checklist-select",
  photoInput: "survey-photo-input",
  photoUploadBtn: "survey-photo-upload-button",
  photoRow: "survey-photo-row",
  saveBtn: "survey-save-button",
  resultSelect: "survey-result-select",
  summaryInput: "survey-summary-input",
  finalizeBtn: "survey-finalize-button",
};

export const COMM_HOME = {
  panel: "commission-breakdown",
  total: "commission-total",
  pending: "commission-pending",
  approved: "commission-approved",
  paid: "commission-paid",
  row: "commission-breakdown-row",
  viewAllBtn: "commission-view-all-button",
};
