// testIds Fase 45 — Target Proyek & Budget/RAB (tab di hub /boq).
// Dipakai gate `verify_budget_target.py` + agen uji E2E untuk menemukan elemen di layar.
export const BUDGET = {
  // tab hub /boq
  targetTab: "tabpage-tab-target",
  realizationTab: "tabpage-tab-realisasi",

  // ---- target
  targetPanel: "budget-target-panel",
  targetSummary: "budget-target-summary",
  targetRow: "budget-target-row",
  targetSelect: "budget-target-select",
  targetCreate: "budget-target-create",
  targetEdit: "budget-target-edit",
  targetDialog: "budget-target-dialog",
  targetName: "budget-target-name",
  targetMethod: "budget-target-method",
  targetBasis: "budget-target-basis",
  targetScope: "budget-target-scope",
  targetStart: "budget-target-start",
  targetEnd: "budget-target-end",
  targetUnit: "budget-target-unit",
  targetRevenue: "budget-target-revenue",
  targetAvgPrice: "budget-target-avgprice",
  targetGrowth: "budget-target-growth",
  targetWeight: "budget-target-weight",
  targetManual: "budget-target-manual",
  targetPreviewBtn: "budget-target-preview-btn",
  targetPreviewTable: "budget-target-preview-table",
  targetPreviewRow: "budget-target-preview-row",
  targetFormula: "budget-target-formula",
  targetSave: "budget-target-save",
  targetActivate: "budget-target-activate",
  targetClose: "budget-target-close",
  targetRecalcBtn: "budget-target-recalc-btn",
  recalcDialog: "budget-recalc-dialog",
  recalcReason: "budget-recalc-reason",
  recalcSubmit: "budget-recalc-submit",
  periodTable: "budget-target-periods",
  periodRow: "budget-target-period-row",
  carryOver: "budget-target-carryover",
  projection: "budget-target-projection",
  history: "budget-target-history",
  targetMissing: "budget-target-missing",

  // ---- master anggaran
  itemsPanel: "budget-items-panel",
  itemRow: "budget-item-row",
  itemCreate: "budget-item-create",
  itemDialog: "budget-item-dialog",
  itemCode: "budget-item-code",
  itemName: "budget-item-name",
  itemCategory: "budget-item-category",
  itemRule: "budget-item-rule",
  itemPlanned: "budget-item-planned",
  itemGl: "budget-item-gl",
  itemOwner: "budget-item-owner",
  itemPeriod: "budget-item-period",
  itemBoq: "budget-item-boq",
  itemBoqOption: "budget-item-boq-option",
  itemSave: "budget-item-save",
  itemDelete: "budget-item-delete",
  itemReadonlyHint: "budget-item-readonly-hint",

  // ---- realisasi 3 lapis
  realizationPanel: "budget-realization-panel",
  summaryCards: "budget-summary-cards",
  warnings: "budget-warnings",
  emptyState: "budget-empty-state",
  categoryTable: "budget-category-table",
  categoryRow: "budget-category-row",
  healthPill: "budget-health-pill",
  drillBtn: "budget-drill-btn",
  drillDialog: "budget-drill-dialog",
  drillDoc: "budget-drill-doc",
  drillTieOut: "budget-drill-tieout",
  drillSource: "budget-drill-source",
  materialInfo: "budget-material-info",
  reviseBtn: "budget-revise-btn",
  reviseDialog: "budget-revise-dialog",
  reviseAmount: "budget-revise-amount",
  reviseReason: "budget-revise-reason",
  reviseSubmit: "budget-revise-submit",
  manualBtn: "budget-manual-btn",
  manualDialog: "budget-manual-dialog",
  manualAmount: "budget-manual-amount",
  manualNote: "budget-manual-note",
  manualSubmit: "budget-manual-submit",

  // ---- laporan pendukung
  marginPanel: "budget-margin-panel",
  unmappedPanel: "budget-unmapped-panel",
  unmappedRow: "budget-unmapped-row",
  enforceBanner: "budget-enforce-banner",
  rabTable: "budget-rab-table",
  rabRow: "budget-rab-row",
  rabGroupBy: "budget-rab-groupby",
  scanBtn: "budget-alert-scan",
  projectTargetCard: "project-target-card",
};
