// Fase 37 — Kalibrasi Sekali Klik: mengubah durasi / waktu tunggu TEMPLATE jadwal
// langsung dari bukti keterlambatan, dengan pratinjau dampak + alasan + pembatalan.
// Setiap elemen yang bisa diklik/diisi punya testid supaya alurnya bisa diuji otomatis.
export const CALIB = {
  page: "build-calibration-page",
  denied: "build-calibration-denied",
  loading: "calibration-loading",
  error: "calibration-error",
  refresh: "calibration-refresh",
  summary: "calibration-summary",
  scope: "calibration-scope",
  project: "calibration-project-select",
  openAnalytics: "calibration-open-analytics",
  openShift: "calibration-open-shift",
  viewerNote: "calibration-viewer-note",
  safetyNote: "calibration-safety-note",
  // usulan dari data telat
  recPanel: "calibration-rec-panel",
  recCard: "calibration-rec-card",
  recApply: "calibration-rec-apply",
  recApplied: "calibration-rec-applied",
  recUndo: "calibration-rec-undo",
  recEmpty: "calibration-rec-empty",
  // tabel langkah yang sering telat
  stepPanel: "calibration-step-panel",
  stepRow: "calibration-step-row",
  stepCalibrate: "calibration-step-calibrate",
  stepApplied: "calibration-step-applied",
  stepEmpty: "calibration-step-empty",
  // template + seluruh langkahnya
  tplPanel: "calibration-template-panel",
  tplSelect: "calibration-template-select",
  tplMeta: "calibration-template-meta",
  tplRow: "calibration-template-step-row",
  tplCalibrate: "calibration-template-calibrate",
  tplApplied: "calibration-template-applied",
  tplEmpty: "calibration-template-empty",
  // dialog kalibrasi (pratinjau = hasil)
  dialog: "calibration-dialog",
  dialogKind: "calibration-kind",
  dialogDelta: "calibration-delta",
  dialogMinus: "calibration-delta-minus",
  dialogPlus: "calibration-delta-plus",
  dialogCause: "calibration-cause",
  dialogNote: "calibration-note",
  dialogExplain: "calibration-explain",
  dialogPreview: "calibration-preview",
  dialogPreviewRow: "calibration-preview-row",
  dialogImpact: "calibration-impact",
  dialogPreviewBtn: "calibration-preview-button",
  dialogHint: "calibration-hint",
  dialogError: "calibration-dialog-error",
  dialogApply: "calibration-apply",
  dialogResult: "calibration-result",
  dialogClose: "calibration-close",
  // riwayat & pembatalan
  histPanel: "calibration-history-panel",
  histRow: "calibration-history-row",
  histRollback: "calibration-history-rollback",
  histReverted: "calibration-history-reverted",
  histEmpty: "calibration-history-empty",
  histAll: "calibration-history-all",
  rbDialog: "calibration-rollback-dialog",
  rbNote: "calibration-rollback-note",
  rbConfirm: "calibration-rollback-confirm",
  rbHint: "calibration-rollback-hint",
  rbError: "calibration-rollback-error",
};
