// Fase 36 — Kalender Jadwal (kalender bulanan tenggat rumah + master kalender kerja).
// Setiap elemen yang bisa diklik/diisi punya testid supaya alur bisa diuji otomatis.
export const CAL = {
  page: "build-calendar-page",
  denied: "build-calendar-denied",
  // toolbar
  scope: "calendar-scope",
  project: "calendar-project-select",
  month: "calendar-month-select",
  prev: "calendar-prev-month",
  next: "calendar-next-month",
  today: "calendar-today",
  refresh: "calendar-refresh",
  kind: "calendar-kind-filter",
  assignee: "calendar-assignee-filter",
  settingsBtn: "calendar-settings-button",
  shiftBtn: "calendar-shift-button",
  // ringkasan & grid
  summary: "calendar-summary",
  grid: "calendar-grid",
  day: "calendar-day",
  dayBadge: "calendar-day-badge",
  legend: "calendar-legend",
  empty: "calendar-empty",
  loading: "calendar-loading",
  // panel hari
  dayPanel: "calendar-day-panel",
  dayEvent: "calendar-day-event",
  dayEventOpen: "calendar-day-event-open",
  dayShift: "calendar-day-shift",
  dayEmpty: "calendar-day-empty",
  dayLoad: "calendar-day-load",
  // bentrok
  conflictPanel: "calendar-conflict-panel",
  conflictRow: "calendar-conflict-row",
  conflictOpen: "calendar-conflict-open",
  conflictShift: "calendar-conflict-shift",
  conflictEmpty: "calendar-conflict-empty",
  outlook: "calendar-outlook",
  outlookRow: "calendar-outlook-row",
  // pengaturan kalender kerja
  settings: "calendar-settings-dialog",
  settingsNote: "calendar-settings-note",
  settingsScope: "calendar-settings-scope",
  settingsInherit: "calendar-settings-inherit",
  overrideDrop: "calendar-override-drop",
  overrideList: "calendar-override-list",
  overrideRow: "calendar-override-row",
  patternRow: "calendar-pattern-row",
  patternSelect: "calendar-pattern-select",
  thresholdItems: "calendar-threshold-items",
  thresholdCritical: "calendar-threshold-critical",
  settingsSave: "calendar-settings-save",
  holidayRow: "calendar-holiday-row",
  holidayDelete: "calendar-holiday-delete",
  holidayExcludedRow: "calendar-holiday-excluded-row",
  holidayRestore: "calendar-holiday-restore",
  holidayDate: "calendar-holiday-date",
  holidayName: "calendar-holiday-name",
  holidayKind: "calendar-holiday-kind",
  holidayAdd: "calendar-holiday-add",
  // inspeksi belum dijadwalkan
  unscheduled: "calendar-unscheduled-panel",
  unscheduledRow: "calendar-unscheduled-row",
  scheduleBtn: "calendar-schedule-inspection",
  scheduleDialog: "calendar-schedule-dialog",
  scheduleDate: "calendar-schedule-date",
  scheduleNote: "calendar-schedule-note",
  scheduleSave: "calendar-schedule-save",
};
