export const FIELD = {
  page: "field-page",
  projectSelect: "field-project-select",
  tabDiary: "field-tab-diary",
  tabPunch: "field-tab-punch",
  diaryPanel: "field-diary-panel",
  punchPanel: "field-punch-panel",
  diaryAddBtn: "diary-add-button",
  diaryAddSubmit: "diary-add-submit",
  diaryRow: "diary-row",
  punchAddBtn: "punch-add-button",
  punchAddSubmit: "punch-add-submit",
  punchRow: "punch-row",
  punchDetail: "punch-detail",
  punchStatusSelect: "punch-status-select",
  punchStatusSubmit: "punch-status-submit",
  // Fase 28b — foto lapangan nyata (object storage, banyak foto per catatan)
  diaryPhotoInput: "diary-photo-input",
  punchPhotoInput: "punch-photo-input",
  fixPhotoInput: "punch-fix-photo-input",
  photoThumb: "photo-upload-thumb",
  photoRemove: "photo-upload-remove",
  gallery: "photo-gallery",
  galleryItem: "photo-gallery-item",
  lightbox: "photo-lightbox",
  // Fase 28b+ — bukti kerja berpasangan (sebelum → sesudah)
  repairs: "repair-evidence",
  repairPair: "repair-pair",
  repairSlider: "repair-compare-slider",
};
