export const GL = {
  accountingPage: "accounting-page",
  reportsPage: "accounting-reports-page",
  // tabs (buku besar)
  coaTab: "gl-tab-coa",
  journalTab: "gl-tab-journal",
  ledgerTab: "gl-tab-ledger",
  tbTab: "gl-tab-tb",
  // CoA
  accountAddBtn: "account-add-button",
  accountAddSubmit: "account-add-submit",
  accountRow: "account-row",
  // Journals
  journalAddBtn: "journal-add-button",
  journalAddSubmit: "journal-add-submit",
  journalLineAdd: "journal-line-add",
  journalMemo: "journal-memo",
  journalDate: "journal-date",
  journalLineRow: "journal-line-row",
  journalLineAccount: "journal-line-account",
  journalLineDebit: "journal-line-debit",
  journalLineCredit: "journal-line-credit",
  journalRow: "journal-row",
  journalDetail: "journal-detail",
  // Ledger
  ledgerAccountSelect: "ledger-account-select",
  ledgerRow: "ledger-row",
  // Trial balance
  tbRow: "trial-balance-row",
  tbBalanced: "trial-balance-balanced",
  // Statements (legacy all-time)
  incomeStatement: "income-statement",
  balanceSheet: "balance-sheet",
  glMetric: "gl-metric",

  // ---------- P25: laporan keuangan berperiode ----------
  tabPl: "gl-tab-pl",
  tabBs: "gl-tab-bs",
  tabWorksheet: "gl-tab-worksheet",
  tabCashflow: "gl-tab-cashflow",
  tabProjects: "gl-tab-projects",
  tabRatios: "gl-tab-ratios",
  tabPeriods: "gl-tab-periods",
  periodFrom: "gl-period-from",
  periodTo: "gl-period-to",
  periodPreset: "gl-period-preset",
  exportBtn: "gl-export-csv",
  refreshBtn: "gl-report-refresh",
  plPanel: "gl-pl-panel",
  plRow: "gl-pl-row",
  plMetric: "gl-pl-metric",
  bsPanel: "gl-bs-panel",
  bsRow: "gl-bs-row",
  bsBalanced: "gl-bs-balanced",
  wsPanel: "gl-worksheet-panel",
  wsRow: "gl-worksheet-row",
  wsBalanced: "gl-worksheet-balanced",
  cfPanel: "gl-cashflow-panel",
  cfRow: "gl-cashflow-row",
  cfReconciled: "gl-cashflow-reconciled",
  projPanel: "gl-projects-panel",
  projRow: "gl-projects-row",
  ratioPanel: "gl-ratios-panel",
  ratioCard: "gl-ratio-card",
  periodsPanel: "gl-periods-panel",
  periodRow: "gl-period-row",
  periodCloseBtn: "gl-period-close-btn",
  periodReopenBtn: "gl-period-reopen-btn",
  drillSheet: "gl-drill-sheet",
  drillRow: "gl-drill-row",
  drillJournal: "gl-drill-journal",
};
