export const HOME = {
  emergentLink: "emergent-link",
  page: "home-page",
  title: "home-title",
  kpiStrip: "kpi-strip",
  metricCard: "metric-card",
  taskInbox: "task-inbox",
  taskCard: "task-card",
  nbaCard: "nba-card",
  quickActions: "quick-actions",
  teamSummary: "home-team-summary",
};

export const NAV = {
  sidebar: "app-sidebar",
  navItemPrefix: "nav-item",
  topbar: "app-topbar",
  pageTitle: "page-title",
  notifBell: "topbar-notif-bell",
  profileMenu: "topbar-profile-menu",
  orgSwitcher: "topbar-org-switcher",
  orgSwitcherItem: "org-switcher-item",
  demoBadge: "topbar-demo-data-badge",
};

export const WORK = {
  tasksPage: "tasks-page",
  taskCompleteBtn: "task-complete-button",
  taskSnoozeBtn: "task-snooze-button",
  filterPrefix: "task-filter",
  emptyState: "empty-state",
  loadingState: "loading-state",
  retryButton: "data-table-retry-button",
  // ---------------- Fase 40d — daftar tugas sebagai TABEL PRO + drill-down KPI ----------
  taskTable: "task-table",
  taskRow: "task-row",
  taskSearch: "task-search",
  bucketPrefix: "task-bucket",
  bulkComplete: "task-bulk-complete",
  bulkSnooze: "task-bulk-snooze",
  bulkExport: "task-bulk-export",
  // ---------------- Fase 29 — Work Hub v2 (divisi, jobdesk, bukti kerja) ----------------
  tabPrefix: "workhub-tab",
  scopePrefix: "work-scope",
  divisionSelect: "work-division-select",
  createTaskBtn: "work-create-task",
  createTaskSubmit: "work-create-task-submit",
  createTaskJobdesk: "work-create-task-jobdesk-select",
  createTaskRelatedType: "work-create-task-related-type-select",
  createTaskRelatedRecord: "work-create-task-related-record-select",
  createTaskRelatedSearch: "work-create-task-related-record-search",
  createTaskRelatedOption: "work-create-task-related-record-option",
  taskOpenBtn: "task-open-button",
  taskLinkBtn: "task-link-button",
  taskDetail: "task-detail-sheet",
  taskStartBtn: "task-start-button",
  taskSubmitBtn: "task-submit-button",
  taskBuildOpenBtn: "task-build-open-button",
  taskBuildRedirect: "task-build-redirect",
  taskSubmitNote: "task-submit-note",
  taskSubmitPhotos: "task-proof-photo-input",
  taskWaManualNote: "task-wa-manual-note",
  taskWaManualEvidence: "task-wa-manual-evidence-input",
  taskWaManualBtn: "task-wa-manual-submit",
  taskVerifyBtn: "task-verify-button",
  taskRejectBtn: "task-reject-button",
  taskRejectReason: "task-reject-reason",
  taskAssignBtn: "task-assign-button",
  taskAssignSelect: "task-assign-select",
  taskAssignSubmit: "task-assign-submit",
  board: "division-board",
  boardMemberRow: "board-member-row",
  boardReviewRow: "board-review-row",
  boardUnassignedRow: "board-unassigned-row",
  boardMetric: "board-metric",
  jobdeskPanel: "jobdesk-panel",
  jobdeskRow: "jobdesk-row",
  jobdeskConfigBtn: "jobdesk-config-button",
  jobdeskRunBtn: "jobdesk-run-button",
  jobdeskSaveBtn: "jobdesk-save-button",
  jobdeskSla: "jobdesk-sla-input",
  jobdeskPriority: "jobdesk-priority-select",
  jobdeskAssigneeRule: "jobdesk-assignee-rule",
  jobdeskAssignee: "jobdesk-assignee-select",
  jobdeskVerify: "jobdesk-verify-select",
  jobdeskActive: "jobdesk-active-toggle",
  kanban: "kanban-board",
  kanbanColumn: "kanban-column",
  report: "division-report",
  reportMetric: "report-metric",
  reportMemberRow: "report-member-row",
  reportEvidence: "report-evidence-item",
  reportPrev: "report-week-prev",
  reportNext: "report-week-next",
  pagination: "pagination",
  pagePrev: "pagination-prev",
  pageNext: "pagination-next",
  pageInfo: "pagination-info",
};

export const ADMIN = {
  usersPage: "admin-users-page",
  usersTable: "admin-users-table",
  permsPage: "admin-permissions-page",
  permsMatrix: "admin-permissions-matrix",
  // Peran dinamis — daftar peran + dialog tambah/ubah/hapus peran kustom.
  rolesPanel: "admin-roles-panel",
  rolesCount: "admin-roles-count",
  rolesAdd: "admin-roles-add",
  rolesError: "admin-roles-error",
  rolesRow: "admin-roles-row",
  rolesEdit: "admin-roles-edit",
  rolesEditScope: "admin-roles-edit-scope",
  rolesScopeOverridden: "admin-roles-scope-overridden",
  rolesCopy: "admin-roles-copy",
  rolesPreview: "admin-roles-preview",
  rolePreviewDialog: "admin-role-preview-dialog",
  rolePreviewList: "admin-role-preview-list",
  rolePreviewCount: "admin-role-preview-count",
  rolePreviewEmpty: "admin-role-preview-empty",
  rolePreviewGroup: "admin-role-preview-group",
  rolePreviewItem: "admin-role-preview-item",
  rolePreviewError: "admin-role-preview-error",
  roleFormPreview: "admin-role-form-preview",
  rolesDelete: "admin-roles-delete",
  rolesDeleteConfirm: "admin-roles-delete-confirm",
  rolesDeleteCancel: "admin-roles-delete-cancel",
  rolesDeleteOk: "admin-roles-delete-ok",
  roleForm: "admin-role-form",
  roleFormLabel: "admin-role-form-label",
  roleFormCode: "admin-role-form-code",
  roleFormDesc: "admin-role-form-desc",
  roleFormInherits: "admin-role-form-inherits",
  roleFormScope: "admin-role-form-scope",
  roleFormCancel: "admin-role-form-cancel",
  roleFormSubmit: "admin-role-form-submit",
  // Fase 51 (utang Phase 0) — layar Hak Akses berhenti berbohong & jadi bisa disunting.
  permsSearch: "admin-permissions-search",
  permsSave: "admin-permissions-save",
  permsReset: "admin-permissions-reset",
  permsRow: "admin-permissions-row",
  permsGroupRow: "admin-permissions-group-row",
  permsResourceLabel: "admin-permissions-resource-label",
  permsCell: "admin-permissions-cell",
  permsCellNone: "admin-permissions-cell-none",
  permsSource: "admin-permissions-source",
  permsEditor: "admin-permissions-editor",
  permsAction: "admin-permissions-action",
  permsCellReset: "admin-permissions-cell-reset",
  permsCellDefault: "admin-permissions-cell-default",
  permsCellClose: "admin-permissions-cell-close",
  permsPending: "admin-permissions-pending",
  permsPendingRow: "admin-permissions-pending-row",
  permsFullAccess: "admin-permissions-full-access",
  permsActionLegend: "admin-permissions-action-legend",
  permsActionLegendRow: "admin-permissions-action-legend-row",
  permsReadonly: "admin-permissions-readonly",
  permsEmpty: "admin-permissions-empty",
  orgsPage: "admin-orgs-page",
  orgRow: "admin-org-row",
  orgAddBtn: "admin-org-add",
  orgName: "admin-org-name",
  orgOwnerName: "admin-org-owner-name",
  orgOwnerEmail: "admin-org-owner-email",
  orgOwnerPassword: "admin-org-owner-password",
  orgCreateSubmit: "admin-org-create-submit",
  orgSwitchBtn: "admin-org-switch",
  orgStatusToggle: "admin-org-status-toggle",
  orgNameText: "admin-org-name",
  orgEditBtn: "admin-org-edit",
  orgEditName: "admin-org-edit-name",
  orgEditSubmit: "admin-org-edit-submit",
};

export const NOTIF = {
  page: "notifications-page",
  item: "notification-item",
  markAll: "notif-mark-all-button",
  // Fase 64 — pusat notifikasi: keadaan (perlu tindakan / belum dibaca / sudah dilihat),
  // kategori, navigasi ke pekerjaannya, dan pembersihan supaya daftar tidak menumpuk.
  stateTab: "notif-state-tab",
  categoryChip: "notif-category-chip",
  search: "notif-search",
  openBtn: "notif-open-button",
  dismissBtn: "notif-dismiss-button",
  clearReadBtn: "notif-clear-read-button",
  actionBadge: "notif-action-badge",
  resolvedNote: "notif-resolved-note",
  summary: "notif-summary",
  empty: "notif-empty",
  // Fase 65 — notifikasi kembar DIKELOMPOKKAN + preferensi saluran per pemakai.
  groupToggle: "notif-group-toggle",
  groupCount: "notif-group-count",
  groupExpand: "notif-group-expand",
  groupMember: "notif-group-member",
  groupReadBtn: "notif-group-read-button",
  groupDismissBtn: "notif-group-dismiss-button",
  prefsBtn: "notif-prefs-button",
  prefsDialog: "notif-prefs-dialog",
  prefsRow: "notif-prefs-row",
  prefsSwitch: "notif-prefs-switch",
  prefsSave: "notif-prefs-save",
  prefsLockNote: "notif-prefs-lock-note",
  waDigestBtn: "notif-wa-digest-button",
  waDigestText: "notif-wa-digest-text",
};
