// EPIC 1.7 Omnichannel test ids (Automation rules, WA templates, Channels, Capture failures).
export const OMNI = {
  page: "omni-page",
  tabRules: "omni-tab-rules",
  tabTemplates: "omni-tab-templates",
  tabChannels: "omni-tab-channels",
  tabBroadcast: "omni-tab-broadcast",
  tabPlaybook: "omni-tab-playbook",
  playbookPanel: "omni-playbook-panel",
  playbookRow: "omni-playbook-row",
  playbookAuto: "omni-playbook-auto",
  playbookCooldown: "omni-playbook-cooldown",
  playbookRun: "omni-playbook-run",
  playbookSend: "omni-playbook-send",
  // rules
  ruleAddBtn: "omni-rule-add",
  ruleRow: "omni-rule-row",
  ruleToggle: "omni-rule-toggle",
  ruleEditBtn: "omni-rule-edit",
  ruleDeleteBtn: "omni-rule-delete",
  ruleName: "omni-rule-name",
  ruleEvent: "omni-rule-event",
  ruleKeywords: "omni-rule-keywords",
  ruleDays: "omni-rule-days",
  ruleSave: "omni-rule-save",
  // templates
  tmplAddBtn: "omni-tmpl-add",
  tmplRow: "omni-tmpl-row",
  tmplName: "omni-tmpl-name",
  tmplBody: "omni-tmpl-body",
  tmplSave: "omni-tmpl-save",
  tmplDeleteBtn: "omni-tmpl-delete",
  // channels
  channelRow: "omni-channel-row",
  channelToggle: "omni-channel-toggle",
  channelAddBtn: "omni-channel-add",
  channelSave: "omni-channel-save",
  // Fase 43: penanda tab & tabel atribusi/CAPI DIHAPUS dari sini — layarnya pindah ke
  // `/attribution` (constants/testIds/ads.js). Menyimpan testId untuk elemen yang sudah
  // tidak ada membuat penguji mengejar sesuatu yang tidak pernah muncul.
  // broadcast / campaign
  bcAddBtn: "omni-bc-add",
  bcRow: "omni-bc-row",
  bcName: "omni-bc-name",
  bcTemplate: "omni-bc-template",
  bcPreviewCount: "omni-bc-preview-count",
  bcSegStage: "omni-bc-seg-stage",
  bcSegScore: "omni-bc-seg-score",
  bcSegSource: "omni-bc-seg-source",
  bcSegCustomers: "omni-bc-seg-customers",
  bcSend: "omni-bc-send",
  bcDetailBtn: "omni-bc-detail",
  bcRecipientRow: "omni-bc-recipient-row",
  // ---------------- Fase 30c — antrean lead gagal masuk (capture.failed) ----------------
  tabCapture: "omni-tab-capture",
  captureBadge: "omni-capture-badge",
  capturePanel: "omni-capture-panel",
  captureSummary: "omni-capture-summary",
  captureStatusFilter: "omni-capture-status-filter",
  captureRefresh: "omni-capture-refresh",
  captureRow: "omni-capture-row",
  captureRaw: "omni-capture-raw",
  captureEmpty: "omni-capture-empty",
  captureFix: "omni-capture-fix",
  captureFixName: "omni-capture-fix-name",
  captureFixPhone: "omni-capture-fix-phone",
  captureFixSource: "omni-capture-fix-source",
  captureRetry: "omni-capture-retry",
  captureDiscard: "omni-capture-discard",
  captureDiscardReason: "omni-capture-discard-reason",
  captureDiscardSubmit: "omni-capture-discard-submit",
  capturePagination: "omni-capture-pagination",
};
