// Fase 100 — Wizard koneksi WhatsApp Cloud API dari antarmuka (Pusat Konfigurasi › Integrasi WhatsApp).
export const P100 = {
  setupPanel: "wa-setup-panel",
  diagnoseBtn: "wa-setup-diagnose-btn",
  problems: "wa-setup-problems",
  tokenInfo: "wa-setup-token-info",
  phoneStatus: "wa-setup-phone-status",
  phoneHint: "wa-setup-phone-hint",
  registerPin: "wa-setup-register-pin",
  registerBtn: "wa-setup-register-btn",
  registerResult: "wa-setup-register-result",
  reverifyToggle: "wa-setup-reverify-toggle",
  codeMethod: "wa-setup-code-method",
  requestCodeBtn: "wa-setup-request-code-btn",
  verifyCodeInput: "wa-setup-verify-code-input",
  verifyCodeBtn: "wa-setup-verify-code-btn",
  subscribedStatus: "wa-setup-subscribed-status",
  subscribeBtn: "wa-setup-subscribe-btn",
  webhookGuide: "wa-webhook-guide",
  webhookUrl: "wa-webhook-url",
  copyUrlBtn: "wa-webhook-copy-url-btn",
  revealTokenBtn: "wa-webhook-reveal-token-btn",
  verifyTokenValue: "wa-webhook-verify-token",
  copyTokenBtn: "wa-webhook-copy-token-btn",
  handshakeBtn: "wa-webhook-handshake-btn",
  handshakeResult: "wa-webhook-handshake-result",
  checklistItem: "wa-checklist-item",
  checklistFix: "wa-checklist-fix",
  goLiveState: "wa-checklist-golive-state",
};
