// Fase 47 — uang masuk & pekerjaan yang bisa dipertanggungjawabkan.
// Rekonsiliasi bank (47A), bukti transfer pelanggan (47B), penawaran (47C),
// absensi & upah harian (47D).
export const BANK = {
  tab: "finance-tab-bank",
  panel: "bank-recon-panel",
  accountSelect: "bank-account-select",
  accountAddBtn: "bank-account-add-button",
  accountSubmit: "bank-account-submit",
  accountName: "bank-account-name",
  accountNo: "bank-account-no",
  accountBankName: "bank-account-bank-name",
  accountGlSelect: "bank-account-gl-select",
  importBtn: "bank-import-button",
  importDialog: "bank-import-dialog",
  importFile: "bank-import-file",
  importText: "bank-import-text",
  importPreviewBtn: "bank-import-preview-button",
  importCommitBtn: "bank-import-commit-button",
  importPreview: "bank-import-preview",
  importRow: "bank-import-row",
  table: "bank-txn-table",
  row: "bank-txn-row",
  reconSummary: "bank-recon-summary",
  reconCause: "bank-recon-cause",
  matchBtn: "bank-match-button",
  matchDialog: "bank-match-dialog",
  matchCandidate: "bank-match-candidate",
  matchSubmit: "bank-match-submit",
  matchKindSelect: "bank-match-kind-select",
  unmatchBtn: "bank-unmatch-button",
  unmatchReason: "bank-unmatch-reason",
  unmatchSubmit: "bank-unmatch-submit",
  ignoreBtn: "bank-ignore-button",
  ignoreReason: "bank-ignore-reason",
  ignoreSubmit: "bank-ignore-submit",
  // Fase 83 — rekonsiliasi per rekening
  overviewTable: "bank-recon-overview",
  overviewRow: "bank-recon-overview-row",
  reconStatus: "bank-recon-status",
  reconDiff: "bank-recon-diff",
  bankOnlyList: "bank-recon-bank-only",
  bookOnlyList: "bank-recon-book-only",
  bookOnlyRow: "bank-recon-book-only-row",
  explainBtn: "bank-recon-explain",
  explainDialog: "bank-recon-explain-dialog",
  explainReason: "bank-recon-explain-reason",
  explainNote: "bank-recon-explain-note",
  explainSubmit: "bank-recon-explain-submit",
  unexplainBtn: "bank-recon-unexplain",
};

export const INTAKE = {
  panel: "payment-intake-panel",
  table: "payment-intake-table",
  row: "payment-intake-row",
  reviewBtn: "payment-intake-review-button",
  reviewDialog: "payment-intake-review-dialog",
  verifyBtn: "payment-intake-verify-button",
  rejectBtn: "payment-intake-reject-button",
  rejectReason: "payment-intake-reject-reason",
  overpayCheck: "payment-intake-overpay-check",
  proofLink: "payment-intake-proof-link",
  // Portal (sisi pelanggan)
  portalSection: "portal-proof-section",
  portalAddBtn: "portal-proof-add-button",
  portalDialog: "portal-proof-dialog",
  portalAmount: "portal-proof-amount",
  portalDate: "portal-proof-date",
  portalFile: "portal-proof-file",
  portalSubmit: "portal-proof-submit",
  portalRow: "portal-proof-row",
};

export const QUOTE = {
  tab: "lead-tab-quotations",
  panel: "quotations-panel",
  addBtn: "quotation-add-button",
  dialog: "quotation-dialog",
  unitSelect: "quotation-unit-select",
  schemeSelect: "quotation-scheme-select",
  addonSelect: "quotation-addon-select",
  addonAddBtn: "quotation-addon-add-button",
  discount: "quotation-discount",
  discountReason: "quotation-discount-reason",
  kprTenor: "quotation-kpr-tenor",
  kprRate: "quotation-kpr-rate",
  kprDp: "quotation-kpr-dp",
  simulateBtn: "quotation-simulate-button",
  breakdown: "quotation-breakdown",
  kprBox: "quotation-kpr-box",
  submitBtn: "quotation-submit-button",
  row: "quotation-row",
  table: "quotations-table",
  detail: "quotation-detail",
  detailBtn: "quotation-detail-button",
  approveBtn: "quotation-approve-button",
  rejectBtn: "quotation-reject-button",
  decisionReason: "quotation-decision-reason",
  decisionSubmit: "quotation-decision-submit",
  sendBtn: "quotation-send-button",
  pdfBtn: "quotation-pdf-button",
  convertBtn: "quotation-convert-button",
  reviseBtn: "quotation-revise-button",
};

export const LABOR = {
  section: "labor-section",
  attendancePanel: "labor-attendance-panel",
  dateInput: "labor-attendance-date",
  workerRow: "labor-attendance-row",
  statusSelect: "labor-attendance-status",
  overtimeInput: "labor-attendance-overtime",
  saveBtn: "labor-attendance-save",
  summary: "labor-attendance-summary",
  diaryCheck: "labor-diary-check",
  workersPanel: "labor-workers-panel",
  workerAddBtn: "labor-worker-add-button",
  workerDialog: "labor-worker-dialog",
  workerName: "labor-worker-name",
  workerRoleSelect: "labor-worker-role-select",
  workerWage: "labor-worker-wage",
  workerSubmit: "labor-worker-submit",
  payrollPanel: "labor-payroll-panel",
  payrollTab: "finance-tab-labor",
  payrollBuildBtn: "labor-payroll-build-button",
  payrollFrom: "labor-payroll-from",
  payrollTo: "labor-payroll-to",
  payrollBuildSubmit: "labor-payroll-build-submit",
  payrollRow: "labor-payroll-row",
  payrollDetail: "labor-payroll-detail",
  payrollDetailBtn: "labor-payroll-detail-button",
  payrollSubmitBtn: "labor-payroll-submit-button",
  payrollApproveBtn: "labor-payroll-approve-button",
  payrollRejectBtn: "labor-payroll-reject-button",
  payrollReason: "labor-payroll-reason",
  payrollDecisionSubmit: "labor-payroll-decision-submit",
  payrollPayBtn: "labor-payroll-pay-button",
  payrollPaySubmit: "labor-payroll-pay-submit",
};
