// Fase 49 — Penutupan Buku, Laporan Owner, Pajak & Kepatuhan.
// Semua elemen yang bisa ditekan/diisi punya testId supaya bisa diuji otomatis.
export const P49 = {
  // ---------- 49A/49B penutupan buku (/accounting?tab=closing) ----------
  closingTab: "gl-tab-closing",
  closingPanel: "p49-closing-panel",
  closingPeriodInput: "p49-closing-period",
  closingPeriodQuick: "p49-closing-period-quick",
  closingRefresh: "p49-closing-refresh",
  closingStatus: "p49-closing-status",
  closingItem: "p49-closing-item",
  closingItemLink: "p49-closing-item-link",
  closingHoldBanner: "p49-closing-hold",
  closingCloseBtn: "p49-closing-close-btn",
  closingOverrideBtn: "p49-closing-override-btn",
  closingOverrideDialog: "p49-closing-override-dialog",
  closingOverrideReason: "p49-closing-override-reason",
  closingOverrideSubmit: "p49-closing-override-submit",
  closingOverrideCancel: "p49-closing-override-cancel",
  closingReopenBtn: "p49-closing-reopen-btn",
  yearPanel: "p49-year-panel",
  yearQuick: "p49-year-quick",
  yearCheckItem: "p49-year-check-item",
  yearRow: "p49-year-row",
  yearCloseBtn: "p49-year-close-btn",
  yearReopenBtn: "p49-year-reopen-btn",
  yearDialog: "p49-year-dialog",
  yearReason: "p49-year-reason",
  yearSubmit: "p49-year-submit",
  yearCancel: "p49-year-cancel",

  // ---------- 49C arus kas per proyek (/accounting/reports) ----------
  cfProjectsTab: "gl-tab-cf-projects",
  cfProjectsPanel: "p49-cfprojects-panel",
  cfProjectRow: "p49-cfproject-row",
  cfUnassignedRow: "p49-cfproject-unassigned",
  cfTieOut: "p49-cfproject-tieout",

  // ---------- 49D paket laporan owner (/accounting/reports) ----------
  ownerPackTab: "gl-tab-owner-pack",
  ownerPackPanel: "p49-ownerpack-panel",
  ownerPackPeriod: "p49-ownerpack-period",
  ownerPackRefresh: "p49-ownerpack-refresh",
  ownerPackTrust: "p49-ownerpack-trust",
  ownerPackMissing: "p49-ownerpack-missing",
  ownerPackSection: "p49-ownerpack-section",
  ownerPackProjectRow: "p49-ownerpack-project-row",
  ownerPackRatio: "p49-ownerpack-ratio",
  closingHistoryRow: "p49-closing-history-row",

  // ---------- 49E e-Faktur ekspor (/tax) ----------
  fakturExportTab: "tax-tab-faktur-export",
  fakturExportPanel: "p49-faktur-export-panel",
  fakturExportPeriod: "p49-faktur-export-period",
  fakturExportPeriodQuick: "p49-faktur-export-period-quick",
  fakturExportCheckBtn: "p49-faktur-export-check-btn",
  fakturExportBlocking: "p49-faktur-export-blocking",
  fakturExportWarning: "p49-faktur-export-warning",
  fakturExportXmlBtn: "p49-faktur-export-xml",
  fakturExportCsvBtn: "p49-faktur-export-csv",
  fakturRow: "p49-faktur-row",
  fakturReplaceBtn: "p49-faktur-replace-btn",
  fakturCancelBtn: "p49-faktur-cancel-btn",
  fakturActionDialog: "p49-faktur-action-dialog",
  fakturActionReason: "p49-faktur-action-reason",
  fakturActionNpwp: "p49-faktur-action-npwp",
  fakturActionDpp: "p49-faktur-action-dpp",
  fakturActionSubmit: "p49-faktur-action-submit",
  fakturActionCancel: "p49-faktur-action-cancel",

  // ---------- 49F bukti potong e-Bupot (/tax) ----------
  bupotTab: "tax-tab-bupot",
  bupotPanel: "p49-bupot-panel",
  bupotPeriod: "p49-bupot-period",
  bupotPeriodQuick: "p49-bupot-period-quick",
  bupotTieOut: "p49-bupot-tieout",
  bupotCandidateRow: "p49-bupot-candidate-row",
  bupotCandidateIssueBtn: "p49-bupot-candidate-issue",
  bupotIssueBtn: "p49-bupot-issue-btn",
  bupotIssueDialog: "p49-bupot-issue-dialog",
  bupotIssueParty: "p49-bupot-issue-party",
  bupotIssueNpwp: "p49-bupot-issue-npwp",
  bupotIssueBase: "p49-bupot-issue-base",
  bupotIssueRate: "p49-bupot-issue-rate",
  bupotIssueKind: "p49-bupot-issue-kind",
  bupotIssuePartyKind: "p49-bupot-issue-party-kind",
  bupotIssueObject: "p49-bupot-issue-object",
  bupotIssueDate: "p49-bupot-issue-date",
  bupotIssueSubmit: "p49-bupot-issue-submit",
  bupotIssueCancel: "p49-bupot-issue-cancel",
  bupotRow: "p49-bupot-row",
  bupotPdfBtn: "p49-bupot-pdf-btn",
  bupotCorrectBtn: "p49-bupot-correct-btn",
  bupotCancelBtn: "p49-bupot-cancel-btn",
  bupotActionDialog: "p49-bupot-action-dialog",
  bupotActionReason: "p49-bupot-action-reason",
  bupotActionBase: "p49-bupot-action-base",
  bupotActionRate: "p49-bupot-action-rate",
  bupotActionSubmit: "p49-bupot-action-submit",
  bupotActionCancel: "p49-bupot-action-cancel",
  bupotExportXmlBtn: "p49-bupot-export-xml",
  bupotExportCsvBtn: "p49-bupot-export-csv",
  bupotExportBlocking: "p49-bupot-export-blocking",

  // ---------- 49G rekap SPT Masa PPN (/tax) ----------
  vatTab: "tax-tab-vat-return",
  vatPanel: "p49-vat-panel",
  vatPeriod: "p49-vat-period",
  vatPeriodQuick: "p49-vat-period-quick",
  vatReconstruct: "p49-vat-reconstruct",
  vatState: "p49-vat-state",

  // ---------- bayar tagihan AP dengan potong PPh (/finance) ----------
  payWithholdToggle: "ap-pay-withhold-toggle",
  payWithholdKind: "ap-pay-withhold-kind",
  payWithholdRate: "ap-pay-withhold-rate",
  payWithholdBase: "ap-pay-withhold-base",
  payWithholdObject: "ap-pay-withhold-object",
  payWithholdPreview: "ap-pay-withhold-preview",
  payCancel: "ap-pay-cancel",
};
