// Fase 50 — Serah Terima Unit (BAST), Masa Garansi & Klaim Garansi Pasca-Huni,
// plus antrean perangkat terpadu (absensi/buku harian/punch list).
// Semua elemen yang bisa ditekan/diisi punya testId supaya bisa diuji otomatis.
export const P50 = {
  // ---------- 50A serah terima (tab di /units/{id}) ----------
  unitTabHandover: "unit-tab-handover",
  handoverPanel: "p50-handover-panel",
  handoverRefresh: "p50-handover-refresh",
  handoverCheckItem: "p50-handover-check-item",
  handoverCheckLink: "p50-handover-check-link",
  handoverHoldBanner: "p50-handover-hold",
  handoverIssueBtn: "p50-handover-issue-btn",
  handoverIssueDialog: "p50-handover-issue-dialog",
  handoverIssueDate: "p50-handover-issue-date",
  handoverIssueReceiver: "p50-handover-issue-receiver",
  handoverIssueWater: "p50-handover-issue-water",
  handoverIssueElectric: "p50-handover-issue-electric",
  handoverIssueKeys: "p50-handover-issue-keys",
  handoverIssueNote: "p50-handover-issue-note",
  handoverIssueOverride: "p50-handover-issue-override",
  handoverIssueReason: "p50-handover-issue-reason",
  handoverIssueSubmit: "p50-handover-issue-submit",
  handoverIssueCancel: "p50-handover-issue-cancel",
  handoverDoc: "p50-handover-doc",
  handoverPdfBtn: "p50-handover-pdf-btn",
  handoverCancelBtn: "p50-handover-cancel-btn",
  handoverCancelDialog: "p50-handover-cancel-dialog",
  handoverCancelReason: "p50-handover-cancel-reason",
  handoverCancelSubmit: "p50-handover-cancel-submit",
  handoverCancelClose: "p50-handover-cancel-close",

  // ---------- 50A masa garansi ----------
  warrantyPanel: "p50-warranty-panel",
  warrantyMissing: "p50-warranty-missing",
  warrantyRow: "p50-warranty-row",
  warrantyPlanRow: "p50-warranty-plan-row",

  // ---------- 50A klaim garansi ----------
  claimNewBtn: "p50-claim-new-btn",
  claimDialog: "p50-claim-dialog",
  claimCategory: "p50-claim-category",
  claimSource: "p50-claim-source",
  claimTitle: "p50-claim-title",
  claimDescription: "p50-claim-description",
  claimSubmit: "p50-claim-submit",
  claimCancel: "p50-claim-cancel",
  claimRow: "p50-claim-row",
  claimState: "p50-claim-state",
  claimRejectNote: "p50-claim-reject-note",
  claimDecideBtn: "p50-claim-decide-btn",
  claimRejectBtn: "p50-claim-reject-btn",
  claimCompleteBtn: "p50-claim-complete-btn",
  claimVerifyBtn: "p50-claim-verify-btn",
  claimReworkBtn: "p50-claim-rework-btn",
  claimCloseBtn: "p50-claim-close-btn",
  claimActionDialog: "p50-claim-action-dialog",
  claimActionReason: "p50-claim-action-reason",
  claimActionRejectReason: "p50-claim-action-reject-reason",
  claimActionAssignee: "p50-claim-action-assignee",
  claimActionPhotos: "p50-claim-action-photos",
  claimActionAck: "p50-claim-action-ack",
  claimActionSubmit: "p50-claim-action-submit",
  claimActionCancel: "p50-claim-action-cancel",

  // ---------- 50A papan garansi & rekap (tab di /construction) ----------
  boardTab: "build-tab-warranty",
  boardPanel: "p50-warranty-board-panel",
  boardRow: "p50-warranty-board-row",
  boardEmpty: "p50-warranty-board-empty",
  claimsPanel: "p50-claims-panel",
  claimsStateFilter: "p50-claims-state-filter",
  claimsCategoryFilter: "p50-claims-category-filter",
  reportCard: "p50-warranty-report",
  reportTieOut: "p50-warranty-report-tieout",
  reportMissing: "p50-warranty-report-missing",
  reportPeriod: "p50-warranty-report-period",

  // ---------- 50A pintu dari komplain CS ----------
  complaintToClaimBtn: "p50-complaint-to-claim-btn",

  // ---------- 50A portal pembeli ----------
  portalTabWarranty: "portal-tab-warranty",
  portalWarrantyPanel: "p50-portal-warranty-panel",
  portalWarrantyRow: "p50-portal-warranty-row",
  portalClaimBtn: "p50-portal-claim-btn",
  portalClaimDialog: "p50-portal-claim-dialog",
  portalClaimCategory: "p50-portal-claim-category",
  portalClaimTitle: "p50-portal-claim-title",
  portalClaimDescription: "p50-portal-claim-description",
  portalClaimSubmit: "p50-portal-claim-submit",
  portalClaimRow: "p50-portal-claim-row",

  // ---------- 50B antrean perangkat terpadu ----------
  queuedBadge: "p50-queued-badge",
  queueOfflineHint: "p50-queue-offline-hint",
};
