// data-testid Fase 57A — skema pembayaran yang bisa dikonfigurasi pemakai.
export const P57 = {
  // Pusat Konfigurasi › Skema Pembayaran
  configTab: "config-tab-scheme",
  panel: "config-scheme-panel",
  row: "config-scheme-row",
  add: "config-scheme-add",
  copy: "config-scheme-copy",
  edit: "config-scheme-edit",
  filterKind: "config-scheme-filter-kind",
  // editor
  dialog: "config-scheme-dialog",
  formName: "config-scheme-name",
  formKind: "config-scheme-kind",
  formActive: "config-scheme-active",
  formDefault: "config-scheme-default",
  formProjects: "config-scheme-projects",
  termRow: "config-scheme-term-row",
  termLabel: "config-scheme-term-label",
  termBasis: "config-scheme-term-basis",
  termValue: "config-scheme-term-value",
  termDueMode: "config-scheme-term-due-mode",
  termDueDay: "config-scheme-term-due-day",
  termOffset: "config-scheme-term-offset",
  termEvent: "config-scheme-term-event",
  termGrace: "config-scheme-term-grace",
  termDelete: "config-scheme-term-delete",
  termAdd: "config-scheme-term-add",
  genOpen: "config-scheme-gen-open",
  genCount: "config-scheme-gen-count",
  genPercent: "config-scheme-gen-percent",
  genDueDay: "config-scheme-gen-due-day",
  genSubmit: "config-scheme-gen-submit",
  previewPrice: "config-scheme-preview-price",
  previewRow: "config-scheme-preview-row",
  previewTotal: "config-scheme-preview-total",
  previewBlocks: "config-scheme-preview-blocks",
  submit: "config-scheme-submit",
  // kontrak
  contractScheme: "contract-payment-scheme",
  contractSchemeBtn: "contract-scheme-change",
  contractSchemeDialog: "contract-scheme-dialog",
  contractSchemeSelect: "contract-scheme-select",
  contractSchemeReason: "contract-scheme-reason",
  contractSchemeSubmit: "contract-scheme-submit",
};
