// Fase 71 — aturan penomoran dokumen & kode master yang bisa dikonfigurasi
export const NUMBERING = {
  tab: "config-tab-numbering",
  panel: "config-numbering-panel",
  table: "numbering-table",
  search: "numbering-search",
  row: "numbering-row",
  groupFilter: "numbering-group-filter",
  projectFilter: "numbering-project-filter",
  edit: "numbering-edit-btn",
  overriddenBadge: "numbering-overridden-badge",
  dialog: "numbering-dialog",
  formPattern: "numbering-form-pattern",
  formPrefix: "numbering-form-prefix",
  formWidth: "numbering-form-width",
  formStart: "numbering-form-start",
  formReset: "numbering-form-reset",
  formScope: "numbering-form-scope",
  preview: "numbering-preview",
  previewError: "numbering-preview-error",
  tokenChip: "numbering-token-chip",
  submit: "numbering-submit",
  resetDefault: "numbering-reset-default",
  cancel: "numbering-cancel",
};
