// Fase 75b-78 — biaya all-in terkonfigurasi, penagihan biaya, pencairan KPR bertahap.
export const P75 = {
  allinSchemeSelect: "allin-scheme-select",
  allinPreview: "allin-scheme-preview",
  allinRow: "allin-component-row",
  allinManualToggle: "allin-manual-toggle",
  allinManualReason: "allin-manual-reason",
  recalcHint: "reserve-recalc-hint",
  addonZeroOverride: "addon-zero-override",
  addonZeroReason: "addon-zero-reason",
  // config
  tabCostComponents: "config-tab-cost-components",
  tabAllin: "config-tab-allin",
  tabKprDisb: "config-tab-kpr-disbursement",
  componentRow: "cost-component-row",
  componentAddBtn: "cost-component-add",
  componentSave: "cost-component-save",
  schemeRow: "allin-scheme-row",
  schemeAddBtn: "allin-scheme-add",
  schemeSave: "allin-scheme-save",
  kprSchemeRow: "kpr-disb-scheme-row",
  kprSchemeAddBtn: "kpr-disb-scheme-add",
  kprSchemeSave: "kpr-disb-scheme-save",
  // kontrak: penagihan biaya
  costPanel: "cost-billing-panel",
  costIssueInvoice: "cost-invoice-issue",
  costInvoiceRow: "cost-invoice-row",
  costPayBtn: "cost-invoice-pay",
  costPayAmount: "cost-pay-amount",
  costPaySubmit: "cost-pay-submit",
  costTitipan: "cost-titipan-balance",
  costDisburseBtn: "cost-disburse-btn",
  costDisburseSubmit: "cost-disburse-submit",
  costExpenseBtn: "cost-expense-btn",
  costExpenseSubmit: "cost-expense-submit",
  costReceiptRow: "cost-receipt-row",
  // KPR pencairan
  kprDisbSchemeSelect: "kpr-disb-scheme-select",
  kprDisbSchemeAssign: "kpr-disb-scheme-assign",
  kprTrancheSelect: "kpr-tranche-select",
  kprDisbRow: "kpr-disbursement-row",
  kprDisbCancel: "kpr-disbursement-cancel",
  kprDisbCancelReason: "kpr-disbursement-cancel-reason",
  kprDisbCancelSubmit: "kpr-disbursement-cancel-submit",
  kprDate: "kpr-date-picker",
  // Fase 79
  amendBox: "allin-amendment-box",
  amendRequestBtn: "allin-amend-request",
  amendSchemeSelect: "allin-amend-scheme",
  amendReason: "allin-amend-reason",
  amendSubmit: "allin-amend-submit",
  amendPending: "allin-amend-pending",
  amendDecideNote: "allin-amend-decide-note",
  amendApprove: "allin-amend-approve",
  amendReject: "allin-amend-reject",
  amendHistoryRow: "allin-amend-history-row",
  costInvoicePdf: "cost-invoice-pdf",
  costReceiptPdf: "cost-receipt-pdf",
  trancheReady: "kpr-tranche-ready",
  trancheReminderPanel: "kpr-tranche-reminder-panel",
  trancheReminderRow: "kpr-tranche-reminder-row",
  trancheReminderRun: "kpr-tranche-reminder-run",
  trancheReminderError: "kpr-tranche-reminder-error",
  amendSchemeError: "allin-amend-scheme-error",
  costPayee: "cost-dialog-payee",
  costNote: "cost-dialog-note",
};
