// Fase 82 — Kas & Bank: master rekening/kas, posisi kas, buku kas & bank, transfer internal.
export const CASHBANK = {
  page: "cashbank-page",
  tabPosition: "cashbank-tab-position",
  tabBook: "cashbank-tab-book",
  tabTransfers: "cashbank-tab-transfers",
  tabAccounts: "cashbank-tab-accounts",
  // posisi kas
  positionSummary: "cashbank-position-summary",
  positionTotal: "cashbank-position-total",
  positionTable: "cashbank-position-table",
  positionRow: "cashbank-position-row",
  negativeAlert: "cashbank-negative-alert",
  // buku kas & bank
  bookAccount: "cashbank-book-account",
  bookFrom: "cashbank-book-from",
  bookTo: "cashbank-book-to",
  bookLoad: "cashbank-book-load",
  bookCsv: "cashbank-book-csv",
  bookOpening: "cashbank-book-opening",
  bookClosing: "cashbank-book-closing",
  bookTable: "cashbank-book-table",
  bookRow: "cashbank-book-row",
  bookEmpty: "cashbank-book-empty",
  // transfer internal
  transferNewBtn: "cashbank-transfer-new",
  transferDialog: "cashbank-transfer-dialog",
  transferKind: "cashbank-transfer-kind",
  transferFrom: "cashbank-transfer-from",
  transferTo: "cashbank-transfer-to",
  transferAmount: "cashbank-transfer-amount",
  transferFee: "cashbank-transfer-fee",
  transferNote: "cashbank-transfer-note",
  transferSubmit: "cashbank-transfer-submit",
  transferTable: "cashbank-transfer-table",
  transferRow: "cashbank-transfer-row",
  transferApprove: "cashbank-transfer-approve",
  transferReject: "cashbank-transfer-reject",
  transferEmpty: "cashbank-transfer-empty",
  // master
  accountNewBtn: "cashbank-account-new",
  accountDialog: "cashbank-account-dialog",
  accountKind: "cashbank-account-kind",
  accountName: "cashbank-account-name",
  accountBank: "cashbank-account-bank",
  accountNo: "cashbank-account-no",
  accountOpening: "cashbank-account-opening",
  accountSubmit: "cashbank-account-submit",
  accountTable: "cashbank-account-table",
  accountRow: "cashbank-account-row",
  accountEdit: "cashbank-account-edit",
  accountSetDefault: "cashbank-account-set-default",
  // pemilih rekening yang disematkan di dialog uang
  select: "cash-account-select",
};
