// Fase 84 — Kas kecil imprest: pengeluaran langsung berbukti + usulan pengisian ulang.
export const PETTYX = {
  tab: "cashbank-tab-petty",
  panel: "petty-expense-panel",
  imprestCards: "petty-imprest-cards",
  imprestCard: "petty-imprest-card",
  imprestStatus: "petty-imprest-status",
  imprestBalance: "petty-imprest-balance",
  imprestReplenish: "petty-imprest-replenish",
  imprestAlert: "petty-imprest-alert",
  newBtn: "petty-expense-new",
  dialog: "petty-expense-dialog",
  account: "petty-expense-account",
  category: "petty-expense-category",
  description: "petty-expense-description",
  amount: "petty-expense-amount",
  date: "petty-expense-date",
  payee: "petty-expense-payee",
  project: "petty-expense-project",
  proof: "petty-expense-proof",
  error: "petty-expense-error",
  submit: "petty-expense-submit",
  filterAccount: "petty-expense-filter-account",
  filterStatus: "petty-expense-filter-status",
  table: "petty-expense-table",
  row: "petty-expense-row",
  empty: "petty-expense-empty",
  sum: "petty-expense-sum",
  voidBtn: "petty-expense-void",
  accountImprest: "cashbank-account-imprest",
};
