// Fase 85–87 — kunci periode kas, giro mundur (PDC), bukti kas BKM/BKK.
export const LOCKS = {
  tab: "cashbank-tab-locks",
  panel: "locks-panel",
  table: "locks-table",
  row: "locks-row",
  lockBtn: "locks-lock-btn",
  unlockBtn: "locks-unlock-btn",
  dialog: "locks-dialog",
  account: "locks-account",
  period: "locks-period",
  counted: "locks-counted",
  preview: "locks-preview",
  previewStatus: "locks-preview-status",
  submit: "locks-submit",
  error: "locks-error",
  history: "locks-history",
};

export const PDC = {
  tab: "cashbank-tab-pdc",
  panel: "pdc-panel",
  summary: "pdc-summary",
  newBtn: "pdc-new",
  dialog: "pdc-dialog",
  kind: "pdc-kind",
  bank: "pdc-bank",
  instrumentNo: "pdc-instrument-no",
  issuer: "pdc-issuer",
  amount: "pdc-amount",
  dueDate: "pdc-due-date",
  dealSearch: "pdc-deal-search",
  dealOption: "pdc-deal-option",
  submit: "pdc-submit",
  error: "pdc-error",
  filterStatus: "pdc-filter-status",
  table: "pdc-table",
  row: "pdc-row",
  empty: "pdc-empty",
  clearBtn: "pdc-clear",
  bounceBtn: "pdc-bounce",
  cancelBtn: "pdc-cancel",
  clearDialog: "pdc-clear-dialog",
  clearAccount: "pdc-clear-account",
  clearDate: "pdc-clear-date",
  clearSubmit: "pdc-clear-submit",
};

export const VOUCHER = {
  tab: "cashbank-tab-vouchers",
  panel: "voucher-panel",
  filterKind: "voucher-filter-kind",
  filterAccount: "voucher-filter-account",
  search: "voucher-search",
  sum: "voucher-sum",
  table: "voucher-table",
  row: "voucher-row",
  empty: "voucher-empty",
  pdfBtn: "voucher-pdf",
  more: "voucher-more",
};
