// Fase 96–98 — WhatsApp: balas cepat, kirim dokumen, dashboard pengiriman, opt-out, template Meta, broadcast antrean.
export const P97 = {
  // balas cepat dari antrean Kontak WA → Lead
  inboxCaptureLink: "inbox-wa-capture-link",
  replyBtn: "wa-contact-reply-btn",
  replyDialog: "wa-reply-dialog",
  replyHistory: "wa-reply-history",
  replyBody: "wa-reply-body",
  replyTemplate: "wa-reply-template",
  replySubmit: "wa-reply-submit",
  replyWindow: "wa-reply-window",
  replySuggestions: "wa-reply-suggestions",
  replySuggestion: "wa-reply-suggestion",
  docSendWaRoute: "docs-send-wa-route",
  tmplHeader: "wa-tmpl-header",
  tmplHeaderBadge: "wa-tmpl-header-badge",
  // kirim dokumen via WA (Dokumen Terbit)
  docSendWaBtn: "docs-send-wa-btn",
  docSendWaReason: "docs-send-wa-reason",
  docWaShares: "docs-wa-shares",
  // Pusat Konfigurasi › Integrasi WhatsApp (sub-tab)
  waTabCreds: "wa-tab-creds",
  waTabDelivery: "wa-tab-delivery",
  waTabOptout: "wa-tab-optout",
  waTabTemplates: "wa-tab-templates",
  // dashboard pengiriman
  deliveryPanel: "wa-delivery-panel",
  deliveryCard: "wa-delivery-card",
  deliveryKindRow: "wa-delivery-kind-row",
  deliveryFailureRow: "wa-delivery-failure-row",
  deliveryDays: "wa-delivery-days",
  deliveryDrill: "wa-delivery-drill",
  deliveryDrillRow: "wa-delivery-drill-row",
  // opt-out
  optoutPanel: "wa-optout-panel",
  optoutSearch: "wa-optout-search",
  optoutRow: "wa-optout-row",
  optoutAddPhone: "wa-optout-add-phone",
  optoutAddBtn: "wa-optout-add-btn",
  optoutExportBtn: "wa-optout-export-btn",
  optoutRevokeBtn: "wa-optout-revoke-btn",
  // template Meta
  tmplMetaPanel: "wa-tmpl-meta-panel",
  tmplMetaRow: "wa-tmpl-meta-row",
  tmplMetaStatus: "wa-tmpl-meta-status",
  tmplSyncBtn: "wa-tmpl-sync-btn",
  tmplSubmitBtn: "wa-tmpl-submit-btn",
  tmplRejectReason: "wa-tmpl-reject-reason",
  tmplExample: "wa-tmpl-example",
  tmplStudio: "wa-tmpl-studio",
  tmplStudioRow: "wa-tmpl-studio-row",
  tmplNewBtn: "wa-tmpl-new-btn",
  tmplEditBtn: "wa-tmpl-edit-btn",
  tmplDeleteBtn: "wa-tmpl-delete-btn",
  tmplUsedBy: "wa-tmpl-used-by",
  tmplHint: "wa-tmpl-hint",
  tmplFrozen: "wa-tmpl-frozen",
  tmplMappingCard: "wa-tmpl-mapping-card",
  tmplMappingRow: "wa-tmpl-mapping-row",
  tmplMappingSelect: "wa-tmpl-mapping-select",
  tmplMappingSave: "wa-tmpl-mapping-save",
  tmplPickerLink: "wa-tmpl-picker-link",
  tmplPreviewBtn: "wa-tmpl-preview-btn",
  // broadcast antrean
  bcStatus: "bc-status",
  bcCounts: "bc-counts",
  bcPauseBtn: "bc-pause-btn",
  bcResumeBtn: "bc-resume-btn",
  bcCancelBtn: "bc-cancel-btn",
  bcRunBtn: "bc-run-btn",
  bcFailures: "bc-failures",
  bcCost: "bc-cost-estimate",
};
