// Kas Bon / Petty Cash (Fase 27) testIds.
export const PETTY = {
  page: "petty-cash-page",
  summary: "petty-cash-summary",
  filter: "petty-cash-status-filter",
  table: "petty-cash-table",
  row: "petty-cash-row",
  empty: "petty-cash-empty",
  requestBtn: "petty-cash-request-button",
  requestDialog: "petty-cash-request-dialog",
  requestPurpose: "petty-cash-request-purpose",
  requestAmount: "petty-cash-request-amount",
  requestCategory: "petty-cash-request-category",
  requestProject: "petty-cash-request-project",
  requestDate: "petty-cash-request-date",
  requestNote: "petty-cash-request-note",
  requestSubmit: "petty-cash-request-submit",
  approveBtn: "petty-cash-approve-button",
  rejectBtn: "petty-cash-reject-button",
  cancelBtn: "petty-cash-cancel-button",
  disburseBtn: "petty-cash-disburse-button",
  disburseDialog: "petty-cash-disburse-dialog",
  disburseAmount: "petty-cash-disburse-amount",
  disburseSource: "petty-cash-disburse-source",
  disburseSubmit: "petty-cash-disburse-submit",
  settleBtn: "petty-cash-settle-button",
  settleDialog: "petty-cash-settle-dialog",
  settleAddItem: "petty-cash-settle-add-item",
  settleItemRow: "petty-cash-settle-item",
  settleItemCategory: "petty-cash-settle-item-category",
  settleItemDesc: "petty-cash-settle-item-desc",
  settleItemAmount: "petty-cash-settle-item-amount",
  settleTotal: "petty-cash-settle-total",
  settleReturned: "petty-cash-settle-returned",
  settleSubmit: "petty-cash-settle-submit",
  detailBtn: "petty-cash-detail-button",
  detailSheet: "petty-cash-detail-sheet",
};
