export const PROCUREMENT = {
  // BoQ / RAB
  boqPage: "boq-page",
  boqProjectSelect: "boq-project-select",
  boqAddBtn: "boq-add-button",
  boqAddSubmit: "boq-add-submit",
  boqRow: "boq-row",
  boqMetric: "boq-metric",
  // Subcontractor + SPK
  subconPage: "subcon-page",
  subTab: "subcon-tab-list",
  spkTab: "subcon-tab-spk",
  subAddBtn: "subcontractor-add-button",
  subAddSubmit: "subcontractor-add-submit",
  subRow: "subcontractor-row",
  subDetail: "subcontractor-detail",
  spkAddBtn: "spk-add-button",
  spkAddSubmit: "spk-add-submit",
  spkRow: "spk-row",
  spkDetail: "spk-detail",
  spkStatusSelect: "spk-status-select",
  spkStatusSubmit: "spk-status-submit",
  // Procurement PO / GRN / 3-way
  procPage: "procurement-page",
  poTab: "procurement-tab-po",
  threewayTab: "procurement-tab-threeway",
  poProjectSelect: "po-project-select",
  poAddBtn: "po-add-button",
  poAddSubmit: "po-add-submit",
  poItemAdd: "po-item-add",
  poRow: "po-row",
  poDetail: "po-detail",
  poApprove: "po-approve-button",
  poCancel: "po-cancel-button",
  grnBtn: "grn-receive-button",
  grnSubmit: "grn-submit",
  billBtn: "bill-create-button",
  billSubmit: "bill-submit",
  matchResult: "match-result",
  threewayRow: "threeway-row",
  procMetric: "procurement-metric",
};
