export const PROFILE = {
  page: "profile-page",
  avatar: "profile-avatar",
  name: "profile-name",
  email: "profile-email",
  role: "profile-role",
  org: "profile-org",
  nameInput: "profile-name-input",
  phoneInput: "profile-phone-input",
  saveBtn: "profile-save-btn",
  pwCurrent: "profile-pw-current",
  pwNew: "profile-pw-new",
  pwConfirm: "profile-pw-confirm",
  pwSubmit: "profile-pw-submit",
  pwError: "profile-pw-error",
  permsList: "profile-perms-list",
  permsItem: "profile-perms-item",
  permsFull: "profile-perms-full",
  activityList: "profile-activity-list",
  activityItem: "profile-activity-item",
  activityEmpty: "profile-activity-empty",
  menuItem: "profile-menu-item",
};
