export const LEADS = {
  page: "leads-page",
  table: "leads-table",
  row: "lead-row",
  addBtn: "lead-add-button",
  simulateBtn: "lead-simulate-button",
  simulateSubmit: "lead-simulate-submit",
  createSubmit: "lead-create-submit",
  searchInput: "lead-search-input",
  pipeline: "lead-pipeline",
  detail: "lead-detail",
  firstContactBtn: "lead-first-contact-button",
  stageBtn: "lead-stage-button",
  reserveBtn: "lead-reserve-button",
  appointmentBtn: "lead-appointment-button",
  // Fase 40 — dialog appointment diangkat keluar dari drawer agar bisa dipakai halaman
  // kanonik /leads/:id (tab Survey).
  apptTitle: "lead-appt-title",
  apptWhen: "lead-appt-when",
  apptLocation: "lead-appt-location",
  apptProject: "lead-appt-project",
  apptSubmit: "lead-appt-submit",
  // Fase 40 — aksi massal pada tabel pipeline
  bulkAssign: "lead-bulk-assign",
  bulkAssignTarget: "lead-bulk-assign-target",
  bulkAssignSubmit: "lead-bulk-assign-submit",
  bulkExport: "lead-bulk-export",
  commentInput: "lead-comment-input",
  commentSubmit: "lead-comment-submit",
  // ---------------- Fase 29b — lifecycle gerbang bukti + WA di record lead ----------------
  lifecycle: "lead-lifecycle",
  stepper: "lead-stage-stepper",
  stepPrefix: "lead-stage-step",
  requirement: "lead-stage-requirement",
  advanceBtn: "lead-stage-advance",
  blockedNote: "lead-stage-blocked",
  closeBtn: "lead-stage-close",
  closeReason: "lead-close-reason-select",
  closeSubmit: "lead-close-submit",
  overrideBtn: "lead-stage-override",
  overrideStage: "lead-override-stage-select",
  overrideReason: "lead-override-reason",
  overrideSubmit: "lead-override-submit",
  historyItem: "lead-stage-history-item",
  nba: "lead-next-actions",
  nbaItem: "lead-next-action-item",
  dispositionBar: "lead-disposition-bar",
  dispositionPrefix: "lead-disposition",
  dispositionNote: "lead-disposition-note",
  dispositionSubmit: "lead-disposition-submit",
  waPanel: "lead-wa-panel",
  waThread: "lead-wa-thread",
  waInput: "lead-wa-input",
  waSend: "lead-wa-send",
  waTemplate: "lead-wa-template-select",
  waWindow: "lead-wa-window-badge",
  waSimulateIn: "lead-wa-simulate-inbound",
  waMessage: "lead-wa-message",
  waManualToggle: "lead-wa-manual-toggle",
  waManualNote: "lead-wa-manual-note",
  waManualEvidence: "lead-wa-manual-evidence-input",
  waManualSubmit: "lead-wa-manual-submit",
  waManualBadge: "lead-wa-manual-badge",
  // ---------------- Fase 30a — pra-skrining BI/SLIK berbukti ----------------
  slikPanel: "lead-slik-panel",
  slikStatus: "lead-slik-status",
  slikOptionPrefix: "lead-slik",
  slikNote: "lead-slik-note",
  slikEvidenceInput: "lead-slik-evidence-input",
  slikEvidenceList: "lead-slik-evidence-list",
  slikRejectedAlert: "lead-slik-rejected-alert",
  slikCloseLead: "lead-slik-close-lead",
  slikTask: "lead-slik-followup-task",
  slikHistoryToggle: "lead-slik-history-toggle",
  slikHistoryItem: "lead-slik-history-item",
};

export const INBOX = {
  page: "inbox-page",
  convItem: "inbox-conv-item",
  thread: "inbox-thread",
  messageInput: "inbox-message-input",
  sendBtn: "inbox-send-button",
  simulateInbound: "inbox-simulate-inbound",
  filterAll: "inbox-filter-all",
  filterMine: "inbox-filter-mine",
  filterUnanswered: "inbox-filter-unanswered",
  windowBadge: "inbox-window-badge",
  templatePick: "inbox-template-pick",
  templateBtn: "inbox-template-send",
  contextPanel: "inbox-context-panel",
  nbaStage: "inbox-nba-stage",
  nbaAppointment: "inbox-nba-appointment",
  nbaIntent: "inbox-nba-intent",
  nbaSuggestion: "inbox-nba-suggestion",
  nbaTemplateSend: "inbox-nba-template-send",
};
export const DEALS = {
  page: "deals-page",
  unitCard: "unit-card",
  reserveBtn: "unit-reserve-button",
  reserveSubmit: "reserve-submit-button",
  dealRow: "deal-row",
  bookBtn: "deal-book-button",
  cancelBtn: "deal-cancel-button",
  createSprBtn: "deal-create-spr-button",
  legalBtn: "deal-legal-button",
  legalDialog: "deal-legal-dialog",
  ppjbSignBtn: "deal-ppjb-sign-button",
  ajbSignBtn: "deal-ajb-sign-button",
  legalNumberInput: "deal-legal-number-input",
  legalNotaryInput: "deal-legal-notary-input",
  legalSubmit: "deal-legal-submit",
  // Fase 40 — tabel pro
  dealTable: "deals-table",
};

export const DOCS = {
  page: "documents-page",
  row: "document-row",
  finalizeBtn: "doc-finalize-button",
  signBtn: "doc-sign-button",
  signSubmit: "doc-sign-submit",
  downloadBtn: "doc-download-button",
};
