// Showroom publik (Fase 28b) — halaman marketing tanpa login.
export const SHOWROOM = {
  page: "showroom-page",
  hero: "showroom-hero",
  headline: "showroom-headline",
  metric: "showroom-metric",
  statusFilter: "showroom-status-filter",
  typeFilter: "showroom-type-filter",
  search: "showroom-search",
  visibleCount: "showroom-visible-count",
  legend: "showroom-legend",
  legendItem: "showroom-legend-item",
  map: "showroom-map",
  list: "showroom-unit-list",
  unitCard: "showroom-unit-card",
  unitSheet: "showroom-unit-sheet",
  unitSheetAsk: "showroom-unit-ask",
  leadBtn: "showroom-lead-button",
  leadDialog: "showroom-lead-dialog",
  leadName: "showroom-lead-name",
  leadPhone: "showroom-lead-phone",
  leadMessage: "showroom-lead-message",
  leadSubmit: "showroom-lead-submit",
  leadSuccess: "showroom-lead-success",
  waBtn: "showroom-wa-button",
  closed: "showroom-closed",
};
