// Tahapan Pembangunan (template fase proyek) & Tahapan Survey — Pusat Konfigurasi.
export const PHASE_TPL = {
  tab: "config-tab-phase-templates",
  panel: "phase-template-panel",
  row: "phase-template-row",
  newBtn: "phase-template-new",
  editBtn: "phase-template-edit",
  deleteBtn: "phase-template-delete",
  formCode: "phase-template-form-code",
  formName: "phase-template-form-name",
  formDesc: "phase-template-form-desc",
  rowName: "phase-template-row-name",
  rowWeight: "phase-template-row-weight",
  rowPlanned: "phase-template-row-planned",
  rowAdd: "phase-template-row-add",
  rowRemove: "phase-template-row-remove",
  rowUp: "phase-template-row-up",
  rowDown: "phase-template-row-down",
  totalWeight: "phase-template-total-weight",
  submit: "phase-template-submit",
  // Detail proyek
  applyOpen: "project-phase-apply-open",
  applySelect: "project-phase-apply-select",
  applySubmit: "project-phase-apply-submit",
  addOpen: "project-phase-add-open",
  addName: "project-phase-add-name",
  addWeight: "project-phase-add-weight",
  addPlanned: "project-phase-add-planned",
  addSubmit: "project-phase-add-submit",
  emptyState: "project-phase-empty",
};

export const SURVEY_STAGES = {
  tab: "config-tab-survey-stages",
  panel: "survey-stage-panel",
  stage: "survey-stage-card",
  stageName: "survey-stage-name",
  stageDesc: "survey-stage-desc",
  stageAdd: "survey-stage-add",
  stageRemove: "survey-stage-remove",
  stageUp: "survey-stage-up",
  stageDown: "survey-stage-down",
  item: "survey-stage-item",
  itemLabel: "survey-stage-item-label",
  itemRequired: "survey-stage-item-required",
  itemAdd: "survey-stage-item-add",
  itemRemove: "survey-stage-item-remove",
  save: "survey-stage-save",
  // Wizard pada form survey
  stepper: "survey-stepper",
  step: "survey-step",
  stepTitle: "survey-step-title",
  prevBtn: "survey-step-prev",
  nextBtn: "survey-step-next",
  requiredBadge: "survey-item-required",
};
